/*
 * Copyright (C) 2012-2013 Intel Mobile Communications GmbH
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#ifndef _IMC_IDI_GNSS_REGS_H
#define _IMC_IDI_GNSS_REGS_H

#define SCU_IMSC_OFFSET           0x200
#define SCU_IMSC(_base) ((_base) + 0x200)
#define SCU_IMSC_C0_OFFSET 0x0
#define SCU_IMSC_C0_WIDTH 0x1
#define SCU_IMSC_C0_MASK 0x1
#define SCU_IMSC_C0(_reg) (((_reg) & 0x1) >> 0x0)
#define SCU_IMSC_C0_DISABLED (0x0 << SCU_IMSC_C0_OFFSET)
#define SCU_IMSC_C0_ENABLED (0x1 << SCU_IMSC_C0_OFFSET)
#define SCU_IMSC_C1_OFFSET 0x1
#define SCU_IMSC_C1_WIDTH 0x1
#define SCU_IMSC_C1_MASK 0x2
#define SCU_IMSC_C1(_reg) (((_reg) & 0x2) >> 0x1)
#define SCU_IMSC_C1_DISABLED (0x0 << SCU_IMSC_C1_OFFSET)
#define SCU_IMSC_C1_ENABLED (0x1 << SCU_IMSC_C1_OFFSET)
#define SCU_IMSC_C2_OFFSET 0x2
#define SCU_IMSC_C2_WIDTH 0x1
#define SCU_IMSC_C2_MASK 0x4
#define SCU_IMSC_C2(_reg) (((_reg) & 0x4) >> 0x2)
#define SCU_IMSC_C2_DISABLED (0x0 << SCU_IMSC_C2_OFFSET)
#define SCU_IMSC_C2_ENABLED (0x1 << SCU_IMSC_C2_OFFSET)
#define SCU_IMSC_C3_OFFSET 0x3
#define SCU_IMSC_C3_WIDTH 0x1
#define SCU_IMSC_C3_MASK 0x8
#define SCU_IMSC_C3(_reg) (((_reg) & 0x8) >> 0x3)
#define SCU_IMSC_C3_DISABLED (0x0 << SCU_IMSC_C3_OFFSET)
#define SCU_IMSC_C3_ENABLED (0x1 << SCU_IMSC_C3_OFFSET)
#define SCU_IMSC_C4_OFFSET 0x4
#define SCU_IMSC_C4_WIDTH 0x1
#define SCU_IMSC_C4_MASK 0x10
#define SCU_IMSC_C4(_reg) (((_reg) & 0x10) >> 0x4)
#define SCU_IMSC_C4_DISABLED (0x0 << SCU_IMSC_C4_OFFSET)
#define SCU_IMSC_C4_ENABLED (0x1 << SCU_IMSC_C4_OFFSET)
#define SCU_IMSC_C5_OFFSET 0x5
#define SCU_IMSC_C5_WIDTH 0x1
#define SCU_IMSC_C5_MASK 0x20
#define SCU_IMSC_C5(_reg) (((_reg) & 0x20) >> 0x5)
#define SCU_IMSC_C5_DISABLED (0x0 << SCU_IMSC_C5_OFFSET)
#define SCU_IMSC_C5_ENABLED (0x1 << SCU_IMSC_C5_OFFSET)
#define SCU_IMSC_C6_OFFSET 0x6
#define SCU_IMSC_C6_WIDTH 0x1
#define SCU_IMSC_C6_MASK 0x40
#define SCU_IMSC_C6(_reg) (((_reg) & 0x40) >> 0x6)
#define SCU_IMSC_C6_DISABLED (0x0 << SCU_IMSC_C6_OFFSET)
#define SCU_IMSC_C6_ENABLED (0x1 << SCU_IMSC_C6_OFFSET)
#define SCU_IMSC_C7_OFFSET 0x7
#define SCU_IMSC_C7_WIDTH 0x1
#define SCU_IMSC_C7_MASK 0x80
#define SCU_IMSC_C7(_reg) (((_reg) & 0x80) >> 0x7)
#define SCU_IMSC_C7_DISABLED (0x0 << SCU_IMSC_C7_OFFSET)
#define SCU_IMSC_C7_ENABLED (0x1 << SCU_IMSC_C7_OFFSET)

#define SCU_GNSS_CTL1_OFFSET    0x0
#define SCU_GNSS_CTL1(_base) ((_base) + 0x0)
#define SCU_GNSS_CTL1_NPORST_OFFSET 0x0
#define SCU_GNSS_CTL1_NPORST_WIDTH 0x1
#define SCU_GNSS_CTL1_NPORST_MASK 0x1
#define SCU_GNSS_CTL1_NPORST(_reg) (((_reg) & 0x1) >> 0x0)
#define SCU_GNSS_CTL1_NPORST_RST (0x0 << SCU_GNSS_CTL1_NPORST_OFFSET)
#define SCU_GNSS_CTL1_NPORST_NORST (0x1 << SCU_GNSS_CTL1_NPORST_OFFSET)
#define SCU_GNSS_CTL1_PMU_RSTN_OFFSET 0x1
#define SCU_GNSS_CTL1_PMU_RSTN_WIDTH 0x1
#define SCU_GNSS_CTL1_PMU_RSTN_MASK 0x2
#define SCU_GNSS_CTL1_PMU_RSTN(_reg) (((_reg) & 0x2) >> 0x1)
#define SCU_GNSS_CTL1_PMU_RSTN_RST (0x0 << SCU_GNSS_CTL1_PMU_RSTN_OFFSET)
#define SCU_GNSS_CTL1_PMU_RSTN_NORST (0x1 << SCU_GNSS_CTL1_PMU_RSTN_OFFSET)
#define SCU_GNSS_CTL1_BB_RSTN_OFFSET 0x2
#define SCU_GNSS_CTL1_BB_RSTN_WIDTH 0x1
#define SCU_GNSS_CTL1_BB_RSTN_MASK 0x4
#define SCU_GNSS_CTL1_BB_RSTN(_reg) (((_reg) & 0x4) >> 0x2)
#define SCU_GNSS_CTL1_BB_RSTN_RST (0x0 << SCU_GNSS_CTL1_BB_RSTN_OFFSET)
#define SCU_GNSS_CTL1_BB_RSTN_NORST (0x1 << SCU_GNSS_CTL1_BB_RSTN_OFFSET)
#define SCU_GNSS_CTL1_WDG_RSTN_OFFSET 0x3
#define SCU_GNSS_CTL1_WDG_RSTN_WIDTH 0x1
#define SCU_GNSS_CTL1_WDG_RSTN_MASK 0x8
#define SCU_GNSS_CTL1_WDG_RSTN(_reg) (((_reg) & 0x8) >> 0x3)
#define SCU_GNSS_CTL1_WDG_RSTN_RST (0x0 << SCU_GNSS_CTL1_WDG_RSTN_OFFSET)
#define SCU_GNSS_CTL1_WDG_RSTN_NORST (0x1 << SCU_GNSS_CTL1_WDG_RSTN_OFFSET)
#define SCU_GNSS_CTL1_DSP_START_OFFSET 0x4
#define SCU_GNSS_CTL1_DSP_START_WIDTH 0x1
#define SCU_GNSS_CTL1_DSP_START_MASK 0x10
#define SCU_GNSS_CTL1_DSP_START(_reg) (((_reg) & 0x10) >> 0x4)
#define SCU_GNSS_CTL1_DSP_START_NOSTART (0x0 << SCU_GNSS_CTL1_DSP_START_OFFSET)
#define SCU_GNSS_CTL1_DSP_START_START (0x1 << SCU_GNSS_CTL1_DSP_START_OFFSET)
#define SCU_GNSS_CTL1_SLEEP_INT_OFFSET 0x5
#define SCU_GNSS_CTL1_SLEEP_INT_WIDTH 0x1
#define SCU_GNSS_CTL1_SLEEP_INT_MASK 0x20
#define SCU_GNSS_CTL1_SLEEP_INT(_reg) (((_reg) & 0x20) >> 0x5)
#define SCU_GNSS_CTL1_SLEEP_INT_NOCHANGE (0x0 << SCU_GNSS_CTL1_SLEEP_INT_OFFSET)
#define SCU_GNSS_CTL1_SLEEP_INT_WAKEUP (0x1 << SCU_GNSS_CTL1_SLEEP_INT_OFFSET)
#define SCU_GNSS_CTL1_NO_EXT_PROC_OFFSET 0x6
#define SCU_GNSS_CTL1_NO_EXT_PROC_WIDTH 0x1
#define SCU_GNSS_CTL1_NO_EXT_PROC_MASK 0x40
#define SCU_GNSS_CTL1_NO_EXT_PROC(_reg) (((_reg) & 0x40) >> 0x6)
#define SCU_GNSS_CTL1_NO_EXT_PROC_EXTPROC \
	(0x0 << SCU_GNSS_CTL1_NO_EXT_PROC_OFFSET)
#define SCU_GNSS_CTL1_NO_EXT_PROC_NOEXTPROC \
	(0x1 << SCU_GNSS_CTL1_NO_EXT_PROC_OFFSET)
#define SCU_GNSS_CTL1_RES1_OFFSET 0x7
#define SCU_GNSS_CTL1_RES1_WIDTH 0x1
#define SCU_GNSS_CTL1_RES1_MASK 0x80
#define SCU_GNSS_CTL1_RES1(_reg) (((_reg) & 0x80) >> 0x7)
#define SCU_GNSS_CTL1_SLEEPB_OFFSET 0x8
#define SCU_GNSS_CTL1_SLEEPB_WIDTH 0x1
#define SCU_GNSS_CTL1_SLEEPB_MASK 0x100
#define SCU_GNSS_CTL1_SLEEPB(_reg) (((_reg) & 0x100) >> 0x8)
#define SCU_GNSS_CTL1_SLEEPB_RET (0x0 << SCU_GNSS_CTL1_SLEEPB_OFFSET)
#define SCU_GNSS_CTL1_SLEEPB_NORET (0x1 << SCU_GNSS_CTL1_SLEEPB_OFFSET)
#define SCU_GNSS_CTL1_POWERONB_OFFSET 0x9
#define SCU_GNSS_CTL1_POWERONB_WIDTH 0x1
#define SCU_GNSS_CTL1_POWERONB_MASK 0x200
#define SCU_GNSS_CTL1_POWERONB(_reg) (((_reg) & 0x200) >> 0x9)
#define SCU_GNSS_CTL1_POWERONB_ON (0x0 << SCU_GNSS_CTL1_POWERONB_OFFSET)
#define SCU_GNSS_CTL1_POWERONB_OFF (0x1 << SCU_GNSS_CTL1_POWERONB_OFFSET)
#define SCU_GNSS_CTL1_GNSS_HP_SW_REQ_OFFSET 0xa
#define SCU_GNSS_CTL1_GNSS_HP_SW_REQ_WIDTH 0x1
#define SCU_GNSS_CTL1_GNSS_HP_SW_REQ_MASK 0x400
#define SCU_GNSS_CTL1_GNSS_HP_SW_REQ(_reg) (((_reg) & 0x400) >> 0xa)
#define SCU_GNSS_CTL1_GNSS_HP_SW_REQ_V_RET \
	(0x0 << SCU_GNSS_CTL1_GNSS_HP_SW_REQ_OFFSET)
#define SCU_GNSS_CTL1_GNSS_HP_SW_REQ_V_HIGH \
	(0x1 << SCU_GNSS_CTL1_GNSS_HP_SW_REQ_OFFSET)
#define SCU_GNSS_CTL1_VDD_HP_SW_REQ_SEL_OFFSET 0xb
#define SCU_GNSS_CTL1_VDD_HP_SW_REQ_SEL_WIDTH 0x1
#define SCU_GNSS_CTL1_VDD_HP_SW_REQ_SEL_MASK 0x800
#define SCU_GNSS_CTL1_VDD_HP_SW_REQ_SEL(_reg) (((_reg) & 0x800) >> 0xb)
#define SCU_GNSS_CTL1_VDD_HP_SW_REQ_SEL_PMU \
	(0x0 << SCU_GNSS_CTL1_VDD_HP_SW_REQ_SEL_OFFSET)
#define SCU_GNSS_CTL1_VDD_HP_SW_REQ_SEL_SW \
	(0x1 << SCU_GNSS_CTL1_VDD_HP_SW_REQ_SEL_OFFSET)
#define SCU_GNSS_CTL1_EXT_REF_CLK_EN_OFFSET 0xc
#define SCU_GNSS_CTL1_EXT_REF_CLK_EN_WIDTH 0x1
#define SCU_GNSS_CTL1_EXT_REF_CLK_EN_MASK 0x1000
#define SCU_GNSS_CTL1_EXT_REF_CLK_EN(_reg) (((_reg) & 0x1000) >> 0xc)
#define SCU_GNSS_CTL1_EXT_REF_CLK_EN_RF \
	(0x0 << SCU_GNSS_CTL1_EXT_REF_CLK_EN_OFFSET)
#define SCU_GNSS_CTL1_EXT_REF_CLK_EN_EXT \
	(0x1 << SCU_GNSS_CTL1_EXT_REF_CLK_EN_OFFSET)
#define SCU_GNSS_CTL1_BOOT_OFFSET 0xd
#define SCU_GNSS_CTL1_BOOT_WIDTH 0x1
#define SCU_GNSS_CTL1_BOOT_MASK 0x2000
#define SCU_GNSS_CTL1_BOOT(_reg) (((_reg) & 0x2000) >> 0xd)
#define SCU_GNSS_CTL1_BOOT_NOJUMP (0x0 << SCU_GNSS_CTL1_BOOT_OFFSET)
#define SCU_GNSS_CTL1_BOOT_JUMP (0x1 << SCU_GNSS_CTL1_BOOT_OFFSET)
#define SCU_GNSS_CTL1_DEBUG_OFFSET 0xe
#define SCU_GNSS_CTL1_DEBUG_WIDTH 0x1
#define SCU_GNSS_CTL1_DEBUG_MASK 0x4000
#define SCU_GNSS_CTL1_DEBUG(_reg) (((_reg) & 0x4000) >> 0xe)
#define SCU_GNSS_CTL1_DEBUG_NODEBUG (0x0 << SCU_GNSS_CTL1_DEBUG_OFFSET)
#define SCU_GNSS_CTL1_DEBUG_DEBUG (0x1 << SCU_GNSS_CTL1_DEBUG_OFFSET)
#define SCU_GNSS_CTL1_PMU_EXTP_OFFSET 0xf
#define SCU_GNSS_CTL1_PMU_EXTP_WIDTH 0x1
#define SCU_GNSS_CTL1_PMU_EXTP_MASK 0x8000
#define SCU_GNSS_CTL1_PMU_EXTP(_reg) (((_reg) & 0x8000) >> 0xf)
#define SCU_GNSS_CTL1_PMU_EXTP_BOOTMODE1 (0x0 << SCU_GNSS_CTL1_PMU_EXTP_OFFSET)
#define SCU_GNSS_CTL1_PMU_EXTP_BOOTMODE2 (0x1 << SCU_GNSS_CTL1_PMU_EXTP_OFFSET)
#define SCU_GNSS_CTL1_BCFG_SEL_OFFSET 0x10
#define SCU_GNSS_CTL1_BCFG_SEL_WIDTH 0x4
#define SCU_GNSS_CTL1_BCFG_SEL_MASK 0xf0000
#define SCU_GNSS_CTL1_BCFG_SEL(_reg) (((_reg) & 0xf0000) >> 0x10)
#define SCU_GNSS_CTL1_ARM_TO_GPS_0_OFFSET 0x14
#define SCU_GNSS_CTL1_ARM_TO_GPS_0_WIDTH 0x1
#define SCU_GNSS_CTL1_ARM_TO_GPS_0_MASK 0x100000
#define SCU_GNSS_CTL1_ARM_TO_GPS_0(_reg) (((_reg) & 0x100000) >> 0x14)
#define SCU_GNSS_CTL1_ARM_TO_GPS_1_OFFSET 0x15
#define SCU_GNSS_CTL1_ARM_TO_GPS_1_WIDTH 0x1
#define SCU_GNSS_CTL1_ARM_TO_GPS_1_MASK 0x200000
#define SCU_GNSS_CTL1_ARM_TO_GPS_1(_reg) (((_reg) & 0x200000) >> 0x15)
#define SCU_GNSS_CTL1_ANA_PATH_ON_RF_OFFSET 0x16
#define SCU_GNSS_CTL1_ANA_PATH_ON_RF_WIDTH 0x1
#define SCU_GNSS_CTL1_ANA_PATH_ON_RF_MASK 0x400000
#define SCU_GNSS_CTL1_ANA_PATH_ON_RF(_reg) (((_reg) & 0x400000) >> 0x16)
#define SCU_GNSS_CTL1_ANA_PATH_ON_RF_DIS \
	(0x0 << SCU_GNSS_CTL1_ANA_PATH_ON_RF_OFFSET)
#define SCU_GNSS_CTL1_ANA_PATH_ON_RF_EN \
	(0x1 << SCU_GNSS_CTL1_ANA_PATH_ON_RF_OFFSET)
#define SCU_GNSS_CTL1_ANA_PATH_ON_DIG_OFFSET 0x17
#define SCU_GNSS_CTL1_ANA_PATH_ON_DIG_WIDTH 0x1
#define SCU_GNSS_CTL1_ANA_PATH_ON_DIG_MASK 0x800000
#define SCU_GNSS_CTL1_ANA_PATH_ON_DIG(_reg) (((_reg) & 0x800000) >> 0x17)
#define SCU_GNSS_CTL1_ANA_PATH_ON_DIG_DIS \
	(0x0 << SCU_GNSS_CTL1_ANA_PATH_ON_DIG_OFFSET)
#define SCU_GNSS_CTL1_ANA_PATH_ON_DIG_EN \
	(0x1 << SCU_GNSS_CTL1_ANA_PATH_ON_DIG_OFFSET)

#define SCU_GNSS_STAT1_OFFSET    0x8
#define SCU_GNSS_STAT1(_base) ((_base) + 0x8)
#define SCU_GNSS_STAT1_WDG_EVENT_RST_OFFSET 0x0
#define SCU_GNSS_STAT1_WDG_EVENT_RST_WIDTH 0x1
#define SCU_GNSS_STAT1_WDG_EVENT_RST_MASK 0x1
#define SCU_GNSS_STAT1_WDG_EVENT_RST(_reg) (((_reg) & 0x1) >> 0x0)
#define SCU_GNSS_STAT1_GPS_DBG_OFFSET 0x1
#define SCU_GNSS_STAT1_GPS_DBG_WIDTH 0x1
#define SCU_GNSS_STAT1_GPS_DBG_MASK 0x2
#define SCU_GNSS_STAT1_GPS_DBG(_reg) (((_reg) & 0x2) >> 0x1)
#define SCU_GNSS_STAT1_GPS_BT_DIS_OFFSET 0x2
#define SCU_GNSS_STAT1_GPS_BT_DIS_WIDTH 0x1
#define SCU_GNSS_STAT1_GPS_BT_DIS_MASK 0x4
#define SCU_GNSS_STAT1_GPS_BT_DIS(_reg) (((_reg) & 0x4) >> 0x2)
#define SCU_GNSS_STAT1_GNSS_PMU_SYS_CLK_REQ_OFFSET 0x3
#define SCU_GNSS_STAT1_GNSS_PMU_SYS_CLK_REQ_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_PMU_SYS_CLK_REQ_MASK 0x8
#define SCU_GNSS_STAT1_GNSS_PMU_SYS_CLK_REQ(_reg) (((_reg) & 0x8) >> 0x3)
#define SCU_GNSS_STAT1_GPS_TCXO_CLK_REQ_OFFSET 0x4
#define SCU_GNSS_STAT1_GPS_TCXO_CLK_REQ_WIDTH 0x1
#define SCU_GNSS_STAT1_GPS_TCXO_CLK_REQ_MASK 0x10
#define SCU_GNSS_STAT1_GPS_TCXO_CLK_REQ(_reg) (((_reg) & 0x10) >> 0x4)
#define SCU_GNSS_STAT1_GPS_RF_CLK_REQ_OFFSET 0x5
#define SCU_GNSS_STAT1_GPS_RF_CLK_REQ_WIDTH 0x1
#define SCU_GNSS_STAT1_GPS_RF_CLK_REQ_MASK 0x20
#define SCU_GNSS_STAT1_GPS_RF_CLK_REQ(_reg) (((_reg) & 0x20) >> 0x5)
#define SCU_GNSS_STAT1_GPS_BB_CLK_REQ_OFFSET 0x6
#define SCU_GNSS_STAT1_GPS_BB_CLK_REQ_WIDTH 0x1
#define SCU_GNSS_STAT1_GPS_BB_CLK_REQ_MASK 0x40
#define SCU_GNSS_STAT1_GPS_BB_CLK_REQ(_reg) (((_reg) & 0x40) >> 0x6)
#define SCU_GNSS_STAT1_GPS_REF_CLK_REQ_OFFSET 0x7
#define SCU_GNSS_STAT1_GPS_REF_CLK_REQ_WIDTH 0x1
#define SCU_GNSS_STAT1_GPS_REF_CLK_REQ_MASK 0x80
#define SCU_GNSS_STAT1_GPS_REF_CLK_REQ(_reg) (((_reg) & 0x80) >> 0x7)
#define SCU_GNSS_STAT1_GPS_TO_ARM_0_OFFSET 0x8
#define SCU_GNSS_STAT1_GPS_TO_ARM_0_WIDTH 0x1
#define SCU_GNSS_STAT1_GPS_TO_ARM_0_MASK 0x100
#define SCU_GNSS_STAT1_GPS_TO_ARM_0(_reg) (((_reg) & 0x100) >> 0x8)
#define SCU_GNSS_STAT1_GPS_TO_ARM_1_OFFSET 0x9
#define SCU_GNSS_STAT1_GPS_TO_ARM_1_WIDTH 0x1
#define SCU_GNSS_STAT1_GPS_TO_ARM_1_MASK 0x200
#define SCU_GNSS_STAT1_GPS_TO_ARM_1(_reg) (((_reg) & 0x200) >> 0x9)
#define SCU_GNSS_STAT1_GPS_EN_LDO_BB_OFFSET 0xa
#define SCU_GNSS_STAT1_GPS_EN_LDO_BB_WIDTH 0x1
#define SCU_GNSS_STAT1_GPS_EN_LDO_BB_MASK 0x400
#define SCU_GNSS_STAT1_GPS_EN_LDO_BB(_reg) (((_reg) & 0x400) >> 0xa)
#define SCU_GNSS_STAT1_GNSS_GPIO_0_OFFSET 0xb
#define SCU_GNSS_STAT1_GNSS_GPIO_0_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_0_MASK 0x800
#define SCU_GNSS_STAT1_GNSS_GPIO_0(_reg) (((_reg) & 0x800) >> 0xb)
#define SCU_GNSS_STAT1_GNSS_GPIO_1_OFFSET 0xc
#define SCU_GNSS_STAT1_GNSS_GPIO_1_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_1_MASK 0x1000
#define SCU_GNSS_STAT1_GNSS_GPIO_1(_reg) (((_reg) & 0x1000) >> 0xc)
#define SCU_GNSS_STAT1_GNSS_GPIO_2_OFFSET 0xd
#define SCU_GNSS_STAT1_GNSS_GPIO_2_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_2_MASK 0x2000
#define SCU_GNSS_STAT1_GNSS_GPIO_2(_reg) (((_reg) & 0x2000) >> 0xd)
#define SCU_GNSS_STAT1_GNSS_GPIO_3_OFFSET 0xe
#define SCU_GNSS_STAT1_GNSS_GPIO_3_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_3_MASK 0x4000
#define SCU_GNSS_STAT1_GNSS_GPIO_3(_reg) (((_reg) & 0x4000) >> 0xe)
#define SCU_GNSS_STAT1_GNSS_GPIO_4_OFFSET 0xf
#define SCU_GNSS_STAT1_GNSS_GPIO_4_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_4_MASK 0x8000
#define SCU_GNSS_STAT1_GNSS_GPIO_4(_reg) (((_reg) & 0x8000) >> 0xf)
#define SCU_GNSS_STAT1_GNSS_GPIO_5_OFFSET 0x10
#define SCU_GNSS_STAT1_GNSS_GPIO_5_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_5_MASK 0x10000
#define SCU_GNSS_STAT1_GNSS_GPIO_5(_reg) (((_reg) & 0x10000) >> 0x10)
#define SCU_GNSS_STAT1_GNSS_GPIO_6_OFFSET 0x11
#define SCU_GNSS_STAT1_GNSS_GPIO_6_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_6_MASK 0x20000
#define SCU_GNSS_STAT1_GNSS_GPIO_6(_reg) (((_reg) & 0x20000) >> 0x11)
#define SCU_GNSS_STAT1_GNSS_GPIO_7_OFFSET 0x12
#define SCU_GNSS_STAT1_GNSS_GPIO_7_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_7_MASK 0x40000
#define SCU_GNSS_STAT1_GNSS_GPIO_7(_reg) (((_reg) & 0x40000) >> 0x12)
#define SCU_GNSS_STAT1_GNSS_GPIO_8_OFFSET 0x13
#define SCU_GNSS_STAT1_GNSS_GPIO_8_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_8_MASK 0x80000
#define SCU_GNSS_STAT1_GNSS_GPIO_8(_reg) (((_reg) & 0x80000) >> 0x13)
#define SCU_GNSS_STAT1_GNSS_GPIO_9_OFFSET 0x14
#define SCU_GNSS_STAT1_GNSS_GPIO_9_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_9_MASK 0x100000
#define SCU_GNSS_STAT1_GNSS_GPIO_9(_reg) (((_reg) & 0x100000) >> 0x14)
#define SCU_GNSS_STAT1_GNSS_GPIO_10_OFFSET 0x15
#define SCU_GNSS_STAT1_GNSS_GPIO_10_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_10_MASK 0x200000
#define SCU_GNSS_STAT1_GNSS_GPIO_10(_reg) (((_reg) & 0x200000) >> 0x15)
#define SCU_GNSS_STAT1_GNSS_GPIO_11_OFFSET 0x16
#define SCU_GNSS_STAT1_GNSS_GPIO_11_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_11_MASK 0x400000
#define SCU_GNSS_STAT1_GNSS_GPIO_11(_reg) (((_reg) & 0x400000) >> 0x16)
#define SCU_GNSS_STAT1_GNSS_GPIO_12_OFFSET 0x17
#define SCU_GNSS_STAT1_GNSS_GPIO_12_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_12_MASK 0x800000
#define SCU_GNSS_STAT1_GNSS_GPIO_12(_reg) (((_reg) & 0x800000) >> 0x17)
#define SCU_GNSS_STAT1_GNSS_GPIO_13_OFFSET 0x18
#define SCU_GNSS_STAT1_GNSS_GPIO_13_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_13_MASK 0x1000000
#define SCU_GNSS_STAT1_GNSS_GPIO_13(_reg) (((_reg) & 0x1000000) >> 0x18)
#define SCU_GNSS_STAT1_GNSS_GPIO_14_OFFSET 0x19
#define SCU_GNSS_STAT1_GNSS_GPIO_14_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_14_MASK 0x2000000
#define SCU_GNSS_STAT1_GNSS_GPIO_14(_reg) (((_reg) & 0x2000000) >> 0x19)
#define SCU_GNSS_STAT1_GNSS_GPIO_15_OFFSET 0x1a
#define SCU_GNSS_STAT1_GNSS_GPIO_15_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_15_MASK 0x4000000
#define SCU_GNSS_STAT1_GNSS_GPIO_15(_reg) (((_reg) & 0x4000000) >> 0x1a)
#define SCU_GNSS_STAT1_GNSS_GPIO_16_OFFSET 0x1b
#define SCU_GNSS_STAT1_GNSS_GPIO_16_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_16_MASK 0x8000000
#define SCU_GNSS_STAT1_GNSS_GPIO_16(_reg) (((_reg) & 0x8000000) >> 0x1b)
#define SCU_GNSS_STAT1_GNSS_GPIO_17_OFFSET 0x1c
#define SCU_GNSS_STAT1_GNSS_GPIO_17_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_17_MASK 0x10000000
#define SCU_GNSS_STAT1_GNSS_GPIO_17(_reg) (((_reg) & 0x10000000) >> 0x1c)
#define SCU_GNSS_STAT1_GNSS_GPIO_18_OFFSET 0x1d
#define SCU_GNSS_STAT1_GNSS_GPIO_18_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_18_MASK 0x20000000
#define SCU_GNSS_STAT1_GNSS_GPIO_18(_reg) (((_reg) & 0x20000000) >> 0x1d)
#define SCU_GNSS_STAT1_GNSS_GPIO_19_OFFSET 0x1e
#define SCU_GNSS_STAT1_GNSS_GPIO_19_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_19_MASK 0x40000000
#define SCU_GNSS_STAT1_GNSS_GPIO_19(_reg) (((_reg) & 0x40000000) >> 0x1e)
#define SCU_GNSS_STAT1_GNSS_GPIO_20_OFFSET 0x1f
#define SCU_GNSS_STAT1_GNSS_GPIO_20_WIDTH 0x1
#define SCU_GNSS_STAT1_GNSS_GPIO_20_MASK 0x80000000
#define SCU_GNSS_STAT1_GNSS_GPIO_20(_reg) (((_reg) & 0x80000000) >> 0x1f)

#define SCU_TES0_OFFSET    0xc
#define SCU_TES0(_base) ((_base) + 0xc)
#define SCU_TES0_GNSS_GPIO_9_OFFSET 0x0
#define SCU_TES0_GNSS_GPIO_9_WIDTH 0x2
#define SCU_TES0_GNSS_GPIO_9_MASK 0x3
#define SCU_TES0_GNSS_GPIO_9(_reg) (((_reg) & 0x3) >> 0x0)
#define SCU_TES0_GNSS_GPIO_10_OFFSET 0x2
#define SCU_TES0_GNSS_GPIO_10_WIDTH 0x2
#define SCU_TES0_GNSS_GPIO_10_MASK 0xc
#define SCU_TES0_GNSS_GPIO_10(_reg) (((_reg) & 0xc) >> 0x2)
#define SCU_TES0_GNSS_GPIO_17_OFFSET 0x4
#define SCU_TES0_GNSS_GPIO_17_WIDTH 0x2
#define SCU_TES0_GNSS_GPIO_17_MASK 0x30
#define SCU_TES0_GNSS_GPIO_17(_reg) (((_reg) & 0x30) >> 0x4)
#define SCU_TES0_GPS_TCXO_CLK_REQ_OFFSET 0x6
#define SCU_TES0_GPS_TCXO_CLK_REQ_WIDTH 0x2
#define SCU_TES0_GPS_TCXO_CLK_REQ_MASK 0xc0
#define SCU_TES0_GPS_TCXO_CLK_REQ(_reg) (((_reg) & 0xc0) >> 0x6)
#define SCU_TES0_GPS_RF_CLK_REQ_OFFSET 0x8
#define SCU_TES0_GPS_RF_CLK_REQ_WIDTH 0x2
#define SCU_TES0_GPS_RF_CLK_REQ_MASK 0x300
#define SCU_TES0_GPS_RF_CLK_REQ(_reg) (((_reg) & 0x300) >> 0x8)
#define SCU_TES0_GPS_BB_CLK_REQ_OFFSET 0xa
#define SCU_TES0_GPS_BB_CLK_REQ_WIDTH 0x2
#define SCU_TES0_GPS_BB_CLK_REQ_MASK 0xc00
#define SCU_TES0_GPS_BB_CLK_REQ(_reg) (((_reg) & 0xc00) >> 0xa)
#define SCU_TES0_GPS_TO_ARM_1_OFFSET 0xc
#define SCU_TES0_GPS_TO_ARM_1_WIDTH 0x2
#define SCU_TES0_GPS_TO_ARM_1_MASK 0x3000
#define SCU_TES0_GPS_TO_ARM_1(_reg) (((_reg) & 0x3000) >> 0xc)
#define SCU_TES0_GPS_TO_ARM_0_OFFSET 0xe
#define SCU_TES0_GPS_TO_ARM_0_WIDTH 0x2
#define SCU_TES0_GPS_TO_ARM_0_MASK 0xc000
#define SCU_TES0_GPS_TO_ARM_0(_reg) (((_reg) & 0xc000) >> 0xe)
#define SCU_TES0_GPS_EN_LDO_BB_OFFSET 0x10
#define SCU_TES0_GPS_EN_LDO_BB_WIDTH 0x2
#define SCU_TES0_GPS_EN_LDO_BB_MASK 0x30000
#define SCU_TES0_GPS_EN_LDO_BB(_reg) (((_reg) & 0x30000) >> 0x10)
#define SCU_TES0_GNSS_GPIO_WAKE_OFFSET 0x12
#define SCU_TES0_GNSS_GPIO_WAKE_WIDTH 0x2
#define SCU_TES0_GNSS_GPIO_WAKE_MASK 0xc0000
#define SCU_TES0_GNSS_GPIO_WAKE(_reg) (((_reg) & 0xc0000) >> 0x12)
#define SCU_TES0_GNSS_GPIO_11_OFFSET 0x14
#define SCU_TES0_GNSS_GPIO_11_WIDTH 0x2
#define SCU_TES0_GNSS_GPIO_11_MASK 0x300000
#define SCU_TES0_GNSS_GPIO_11(_reg) (((_reg) & 0x300000) >> 0x14)
#define SCU_TES0_GNSS_GPIO_12_OFFSET 0x16
#define SCU_TES0_GNSS_GPIO_12_WIDTH 0x2
#define SCU_TES0_GNSS_GPIO_12_MASK 0xc00000
#define SCU_TES0_GNSS_GPIO_12(_reg) (((_reg) & 0xc00000) >> 0x16)

#define SCU_FEN0_OFFSET    0x10
#define SCU_FEN0(_base) ((_base) + 0x10)
#define SCU_FEN0_GNSS_GPIO_9_OFFSET 0x0
#define SCU_FEN0_GNSS_GPIO_9_WIDTH 0x2
#define SCU_FEN0_GNSS_GPIO_9_MASK 0x3
#define SCU_FEN0_GNSS_GPIO_9(_reg) (((_reg) & 0x3) >> 0x0)
#define SCU_FEN0_GNSS_GPIO_10_OFFSET 0x2
#define SCU_FEN0_GNSS_GPIO_10_WIDTH 0x2
#define SCU_FEN0_GNSS_GPIO_10_MASK 0xc
#define SCU_FEN0_GNSS_GPIO_10(_reg) (((_reg) & 0xc) >> 0x2)
#define SCU_FEN0_GNSS_GPIO_17_OFFSET 0x4
#define SCU_FEN0_GNSS_GPIO_17_WIDTH 0x2
#define SCU_FEN0_GNSS_GPIO_17_MASK 0x30
#define SCU_FEN0_GNSS_GPIO_17(_reg) (((_reg) & 0x30) >> 0x4)
#define SCU_FEN0_GPS_TCXO_CLK_REQ_OFFSET 0x6
#define SCU_FEN0_GPS_TCXO_CLK_REQ_WIDTH 0x2
#define SCU_FEN0_GPS_TCXO_CLK_REQ_MASK 0xc0
#define SCU_FEN0_GPS_TCXO_CLK_REQ(_reg) (((_reg) & 0xc0) >> 0x6)
#define SCU_FEN0_GPS_RF_CLK_REQ_OFFSET 0x8
#define SCU_FEN0_GPS_RF_CLK_REQ_WIDTH 0x2
#define SCU_FEN0_GPS_RF_CLK_REQ_MASK 0x300
#define SCU_FEN0_GPS_RF_CLK_REQ(_reg) (((_reg) & 0x300) >> 0x8)
#define SCU_FEN0_GPS_BB_CLK_REQ_OFFSET 0xa
#define SCU_FEN0_GPS_BB_CLK_REQ_WIDTH 0x2
#define SCU_FEN0_GPS_BB_CLK_REQ_MASK 0xc00
#define SCU_FEN0_GPS_BB_CLK_REQ(_reg) (((_reg) & 0xc00) >> 0xa)
#define SCU_FEN0_GPS_TO_ARM_1_OFFSET 0xc
#define SCU_FEN0_GPS_TO_ARM_1_WIDTH 0x2
#define SCU_FEN0_GPS_TO_ARM_1_MASK 0x3000
#define SCU_FEN0_GPS_TO_ARM_1(_reg) (((_reg) & 0x3000) >> 0xc)
#define SCU_FEN0_GPS_TO_ARM_0_OFFSET 0xe
#define SCU_FEN0_GPS_TO_ARM_0_WIDTH 0x2
#define SCU_FEN0_GPS_TO_ARM_0_MASK 0xc000
#define SCU_FEN0_GPS_TO_ARM_0(_reg) (((_reg) & 0xc000) >> 0xe)
#define SCU_FEN0_GPS_EN_LDO_BB_OFFSET 0x10
#define SCU_FEN0_GPS_EN_LDO_BB_WIDTH 0x2
#define SCU_FEN0_GPS_EN_LDO_BB_MASK 0x30000
#define SCU_FEN0_GPS_EN_LDO_BB(_reg) (((_reg) & 0x30000) >> 0x10)
#define SCU_FEN0_GNSS_GPIO_WAKE_OFFSET 0x12
#define SCU_FEN0_GNSS_GPIO_WAKE_WIDTH 0x2
#define SCU_FEN0_GNSS_GPIO_WAKE_MASK 0xc0000
#define SCU_FEN0_GNSS_GPIO_WAKE(_reg) (((_reg) & 0xc0000) >> 0x12)
#define SCU_FEN0_GNSS_GPIO_11_OFFSET 0x14
#define SCU_FEN0_GNSS_GPIO_11_WIDTH 0x2
#define SCU_FEN0_GNSS_GPIO_11_MASK 0x300000
#define SCU_FEN0_GNSS_GPIO_11(_reg) (((_reg) & 0x300000) >> 0x14)
#define SCU_FEN0_GNSS_GPIO_12_OFFSET 0x16
#define SCU_FEN0_GNSS_GPIO_12_WIDTH 0x2
#define SCU_FEN0_GNSS_GPIO_12_MASK 0xc00000
#define SCU_FEN0_GNSS_GPIO_12(_reg) (((_reg) & 0xc00000) >> 0x16)

#define SCU_LEN0_OFFSET    0x14
#define SCU_LEN0(_base) ((_base) + 0x14)
#define SCU_LEN0_GNSS_GPIO_9_OFFSET 0x0
#define SCU_LEN0_GNSS_GPIO_9_WIDTH 0x2
#define SCU_LEN0_GNSS_GPIO_9_MASK 0x3
#define SCU_LEN0_GNSS_GPIO_9(_reg) (((_reg) & 0x3) >> 0x0)
#define SCU_LEN0_GNSS_GPIO_10_OFFSET 0x2
#define SCU_LEN0_GNSS_GPIO_10_WIDTH 0x2
#define SCU_LEN0_GNSS_GPIO_10_MASK 0xc
#define SCU_LEN0_GNSS_GPIO_10(_reg) (((_reg) & 0xc) >> 0x2)
#define SCU_LEN0_GNSS_GPIO_17_OFFSET 0x4
#define SCU_LEN0_GNSS_GPIO_17_WIDTH 0x2
#define SCU_LEN0_GNSS_GPIO_17_MASK 0x30
#define SCU_LEN0_GNSS_GPIO_17(_reg) (((_reg) & 0x30) >> 0x4)
#define SCU_LEN0_GPS_TCXO_CLK_REQ_OFFSET 0x6
#define SCU_LEN0_GPS_TCXO_CLK_REQ_WIDTH 0x2
#define SCU_LEN0_GPS_TCXO_CLK_REQ_MASK 0xc0
#define SCU_LEN0_GPS_TCXO_CLK_REQ(_reg) (((_reg) & 0xc0) >> 0x6)
#define SCU_LEN0_GPS_RF_CLK_REQ_OFFSET 0x8
#define SCU_LEN0_GPS_RF_CLK_REQ_WIDTH 0x2
#define SCU_LEN0_GPS_RF_CLK_REQ_MASK 0x300
#define SCU_LEN0_GPS_RF_CLK_REQ(_reg) (((_reg) & 0x300) >> 0x8)
#define SCU_LEN0_GPS_BB_CLK_REQ_OFFSET 0xa
#define SCU_LEN0_GPS_BB_CLK_REQ_WIDTH 0x2
#define SCU_LEN0_GPS_BB_CLK_REQ_MASK 0xc00
#define SCU_LEN0_GPS_BB_CLK_REQ(_reg) (((_reg) & 0xc00) >> 0xa)
#define SCU_LEN0_GPS_TO_ARM_1_OFFSET 0xc
#define SCU_LEN0_GPS_TO_ARM_1_WIDTH 0x2
#define SCU_LEN0_GPS_TO_ARM_1_MASK 0x3000
#define SCU_LEN0_GPS_TO_ARM_1(_reg) (((_reg) & 0x3000) >> 0xc)
#define SCU_LEN0_GPS_TO_ARM_0_OFFSET 0xe
#define SCU_LEN0_GPS_TO_ARM_0_WIDTH 0x2
#define SCU_LEN0_GPS_TO_ARM_0_MASK 0xc000
#define SCU_LEN0_GPS_TO_ARM_0(_reg) (((_reg) & 0xc000) >> 0xe)
#define SCU_LEN0_GPS_EN_LDO_BB_OFFSET 0x10
#define SCU_LEN0_GPS_EN_LDO_BB_WIDTH 0x2
#define SCU_LEN0_GPS_EN_LDO_BB_MASK 0x30000
#define SCU_LEN0_GPS_EN_LDO_BB(_reg) (((_reg) & 0x30000) >> 0x10)
#define SCU_LEN0_GNSS_GPIO_WAKE_OFFSET 0x12
#define SCU_LEN0_GNSS_GPIO_WAKE_WIDTH 0x2
#define SCU_LEN0_GNSS_GPIO_WAKE_MASK 0xc0000
#define SCU_LEN0_GNSS_GPIO_WAKE(_reg) (((_reg) & 0xc0000) >> 0x12)
#define SCU_LEN0_GNSS_GPIO_11_OFFSET 0x14
#define SCU_LEN0_GNSS_GPIO_11_WIDTH 0x2
#define SCU_LEN0_GNSS_GPIO_11_MASK 0x300000
#define SCU_LEN0_GNSS_GPIO_11(_reg) (((_reg) & 0x300000) >> 0x14)
#define SCU_LEN0_GNSS_GPIO_12_OFFSET 0x16
#define SCU_LEN0_GNSS_GPIO_12_WIDTH 0x2
#define SCU_LEN0_GNSS_GPIO_12_MASK 0xc00000
#define SCU_LEN0_GNSS_GPIO_12(_reg) (((_reg) & 0xc00000) >> 0x16)

#define SCU_C5_IRQSM_OFFSET    0x18
#define SCU_C5_IRQSM(_base) ((_base) + 0x18)
#define SCU_C5_IRQSM_GPS_EN_LDO_BB_OFFSET 0x0
#define SCU_C5_IRQSM_GPS_EN_LDO_BB_WIDTH 0x1
#define SCU_C5_IRQSM_GPS_EN_LDO_BB_MASK 0x1
#define SCU_C5_IRQSM_GPS_EN_LDO_BB(_reg) (((_reg) & 0x1) >> 0x0)
#define SCU_C5_IRQSM_GPS_EN_LDO_BB_DISABLED \
	(0x0 << SCU_C5_IRQSM_GPS_EN_LDO_BB_OFFSET)
#define SCU_C5_IRQSM_GPS_EN_LDO_BB_ENABLED \
	(0x1 << SCU_C5_IRQSM_GPS_EN_LDO_BB_OFFSET)
#define SCU_C5_IRQSM_GNSS_GPIO_WAKE_OFFSET 0x1
#define SCU_C5_IRQSM_GNSS_GPIO_WAKE_WIDTH 0x1
#define SCU_C5_IRQSM_GNSS_GPIO_WAKE_MASK 0x2
#define SCU_C5_IRQSM_GNSS_GPIO_WAKE(_reg) (((_reg) & 0x2) >> 0x1)
#define SCU_C5_IRQSM_GNSS_GPIO_WAKE_DISABLED \
	(0x0 << SCU_C5_IRQSM_GNSS_GPIO_WAKE_OFFSET)
#define SCU_C5_IRQSM_GNSS_GPIO_WAKE_ENABLED \
	(0x1 << SCU_C5_IRQSM_GNSS_GPIO_WAKE_OFFSET)
#define SCU_C5_IRQSM_GPS_TO_ARM_0_OFFSET 0x2
#define SCU_C5_IRQSM_GPS_TO_ARM_0_WIDTH 0x1
#define SCU_C5_IRQSM_GPS_TO_ARM_0_MASK 0x4
#define SCU_C5_IRQSM_GPS_TO_ARM_0(_reg) (((_reg) & 0x4) >> 0x2)
#define SCU_C5_IRQSM_GPS_TO_ARM_0_DISABLED \
	(0x0 << SCU_C5_IRQSM_GPS_TO_ARM_0_OFFSET)
#define SCU_C5_IRQSM_GPS_TO_ARM_0_ENABLED \
	(0x1 << SCU_C5_IRQSM_GPS_TO_ARM_0_OFFSET)

#define SCU_C5_IRQSS_OFFSET    0x1c
#define SCU_C5_IRQSS(_base) ((_base) + 0x1c)
#define SCU_C5_IRQSS_GPS_EN_LDO_BB_OFFSET 0x0
#define SCU_C5_IRQSS_GPS_EN_LDO_BB_WIDTH 0x1
#define SCU_C5_IRQSS_GPS_EN_LDO_BB_MASK 0x1
#define SCU_C5_IRQSS_GPS_EN_LDO_BB(_reg) (((_reg) & 0x1) >> 0x0)
#define SCU_C5_IRQSS_GPS_EN_LDO_BB_NO_INTERRUPT \
	(0x0 << SCU_C5_IRQSS_GPS_EN_LDO_BB_OFFSET)
#define SCU_C5_IRQSS_GPS_EN_LDO_BB_PENDING_INTERRUPT \
	(0x1 << SCU_C5_IRQSS_GPS_EN_LDO_BB_OFFSET)
#define SCU_C5_IRQSS_GNSS_GPIO_WAKE_OFFSET 0x1
#define SCU_C5_IRQSS_GNSS_GPIO_WAKE_WIDTH 0x1
#define SCU_C5_IRQSS_GNSS_GPIO_WAKE_MASK 0x2
#define SCU_C5_IRQSS_GNSS_GPIO_WAKE(_reg) (((_reg) & 0x2) >> 0x1)
#define SCU_C5_IRQSS_GNSS_GPIO_WAKE_NO_INTERRUPT \
	(0x0 << SCU_C5_IRQSS_GNSS_GPIO_WAKE_OFFSET)
#define SCU_C5_IRQSS_GNSS_GPIO_WAKE_PENDING_INTERRUPT \
	(0x1 << SCU_C5_IRQSS_GNSS_GPIO_WAKE_OFFSET)
#define SCU_C5_IRQSS_GPS_TO_ARM_0_OFFSET 0x2
#define SCU_C5_IRQSS_GPS_TO_ARM_0_WIDTH 0x1
#define SCU_C5_IRQSS_GPS_TO_ARM_0_MASK 0x4
#define SCU_C5_IRQSS_GPS_TO_ARM_0(_reg) (((_reg) & 0x4) >> 0x2)
#define SCU_C5_IRQSS_GPS_TO_ARM_0_NO_INTERRUPT \
	(0x0 << SCU_C5_IRQSS_GPS_TO_ARM_0_OFFSET)
#define SCU_C5_IRQSS_GPS_TO_ARM_0_PENDING_INTERRUPT \
	(0x1 << SCU_C5_IRQSS_GPS_TO_ARM_0_OFFSET)

#define SCU_C5_IRQSC_OFFSET    0x20
#define SCU_C5_IRQSC(_base) ((_base) + 0x20)
#define SCU_C5_IRQSC_GPS_EN_LDO_BB_OFFSET 0x0
#define SCU_C5_IRQSC_GPS_EN_LDO_BB_WIDTH 0x1
#define SCU_C5_IRQSC_GPS_EN_LDO_BB_MASK 0x1
#define SCU_C5_IRQSC_GPS_EN_LDO_BB(_reg) (((_reg) & 0x1) >> 0x0)
#define SCU_C5_IRQSC_GPS_EN_LDO_BB_NO_CHANGE \
	(0x0 << SCU_C5_IRQSC_GPS_EN_LDO_BB_OFFSET)
#define SCU_C5_IRQSC_GPS_EN_LDO_BB_CLEAR_INTERRUPT \
	(0x1 << SCU_C5_IRQSC_GPS_EN_LDO_BB_OFFSET)
#define SCU_C5_IRQSC_GNSS_GPIO_WAKE_OFFSET 0x1
#define SCU_C5_IRQSC_GNSS_GPIO_WAKE_WIDTH 0x1
#define SCU_C5_IRQSC_GNSS_GPIO_WAKE_MASK 0x2
#define SCU_C5_IRQSC_GNSS_GPIO_WAKE(_reg) (((_reg) & 0x2) >> 0x1)
#define SCU_C5_IRQSC_GNSS_GPIO_WAKE_NO_CHANGE \
	(0x0 << SCU_C5_IRQSC_GNSS_GPIO_WAKE_OFFSET)
#define SCU_C5_IRQSC_GNSS_GPIO_WAKE_CLEAR_INTERRUPT \
	(0x1 << SCU_C5_IRQSC_GNSS_GPIO_WAKE_OFFSET)
#define SCU_C5_IRQSC_GPS_TO_ARM_0_OFFSET 0x2
#define SCU_C5_IRQSC_GPS_TO_ARM_0_WIDTH 0x1
#define SCU_C5_IRQSC_GPS_TO_ARM_0_MASK 0x4
#define SCU_C5_IRQSC_GPS_TO_ARM_0(_reg) (((_reg) & 0x4) >> 0x2)
#define SCU_C5_IRQSC_GPS_TO_ARM_0_NO_CHANGE \
	(0x0 << SCU_C5_IRQSC_GPS_TO_ARM_0_OFFSET)
#define SCU_C5_IRQSC_GPS_TO_ARM_0_CLEAR_INTERRUPT \
	(0x1 << SCU_C5_IRQSC_GPS_TO_ARM_0_OFFSET)

#define SCU_C6_IRQSM_OFFSET    0x24
#define SCU_C6_IRQSM(_base) ((_base) + 0x24)
#define SCU_C6_IRQSM_WDG_EVENT_RST_OFFSET 0x0
#define SCU_C6_IRQSM_WDG_EVENT_RST_WIDTH 0x1
#define SCU_C6_IRQSM_WDG_EVENT_RST_MASK 0x1
#define SCU_C6_IRQSM_WDG_EVENT_RST(_reg) (((_reg) & 0x1) >> 0x0)
#define SCU_C6_IRQSM_WDG_EVENT_RST_DISABLED \
	(0x0 << SCU_C6_IRQSM_WDG_EVENT_RST_OFFSET)
#define SCU_C6_IRQSM_WDG_EVENT_RST_ENABLED \
	(0x1 << SCU_C6_IRQSM_WDG_EVENT_RST_OFFSET)

#define SCU_C6_IRQSS_OFFSET    0x28
#define SCU_C6_IRQSS(_base) ((_base) + 0x28)
#define SCU_C6_IRQSS_WDG_EVENT_RST_OFFSET 0x0
#define SCU_C6_IRQSS_WDG_EVENT_RST_WIDTH 0x1
#define SCU_C6_IRQSS_WDG_EVENT_RST_MASK 0x1
#define SCU_C6_IRQSS_WDG_EVENT_RST(_reg) (((_reg) & 0x1) >> 0x0)
#define SCU_C6_IRQSS_WDG_EVENT_RST_NO_INTERRUPT \
	(0x0 << SCU_C6_IRQSS_WDG_EVENT_RST_OFFSET)
#define SCU_C6_IRQSS_WDG_EVENT_RST_PENDING_INTERRUPT \
	(0x1 << SCU_C6_IRQSS_WDG_EVENT_RST_OFFSET)

#define SCU_C6_IRQSC_OFFSET    0x2c
#define SCU_C6_IRQSC(_base) ((_base) + 0x2c)
#define SCU_C6_IRQSC_WDG_EVENT_RST_OFFSET 0x0
#define SCU_C6_IRQSC_WDG_EVENT_RST_WIDTH 0x1
#define SCU_C6_IRQSC_WDG_EVENT_RST_MASK 0x1
#define SCU_C6_IRQSC_WDG_EVENT_RST(_reg) (((_reg) & 0x1) >> 0x0)
#define SCU_C6_IRQSC_WDG_EVENT_RST_NO_CHANGE \
	(0x0 << SCU_C6_IRQSC_WDG_EVENT_RST_OFFSET)
#define SCU_C6_IRQSC_WDG_EVENT_RST_CLEAR_INTERRUPT \
	(0x1 << SCU_C6_IRQSC_WDG_EVENT_RST_OFFSET)

#define SCU_C7_IRQSM_OFFSET    0x30
#define SCU_C7_IRQSM(_base) ((_base) + 0x30)
#define SCU_C7_IRQSM_GPS_DBG_OFFSET 0x0
#define SCU_C7_IRQSM_GPS_DBG_WIDTH 0x1
#define SCU_C7_IRQSM_GPS_DBG_MASK 0x1
#define SCU_C7_IRQSM_GPS_DBG(_reg) (((_reg) & 0x1) >> 0x0)
#define SCU_C7_IRQSM_GPS_DBG_DISABLED (0x0 << SCU_C7_IRQSM_GPS_DBG_OFFSET)
#define SCU_C7_IRQSM_GPS_DBG_ENABLED (0x1 << SCU_C7_IRQSM_GPS_DBG_OFFSET)
#define SCU_C7_IRQSM_GPS_TCXO_CLK_REQ_OFFSET 0x1
#define SCU_C7_IRQSM_GPS_TCXO_CLK_REQ_WIDTH 0x1
#define SCU_C7_IRQSM_GPS_TCXO_CLK_REQ_MASK 0x2
#define SCU_C7_IRQSM_GPS_TCXO_CLK_REQ(_reg) (((_reg) & 0x2) >> 0x1)
#define SCU_C7_IRQSM_GPS_TCXO_CLK_REQ_DISABLED \
	(0x0 << SCU_C7_IRQSM_GPS_TCXO_CLK_REQ_OFFSET)
#define SCU_C7_IRQSM_GPS_TCXO_CLK_REQ_ENABLED \
	(0x1 << SCU_C7_IRQSM_GPS_TCXO_CLK_REQ_OFFSET)
#define SCU_C7_IRQSM_GPS_RF_CLK_REQ_OFFSET 0x2
#define SCU_C7_IRQSM_GPS_RF_CLK_REQ_WIDTH 0x1
#define SCU_C7_IRQSM_GPS_RF_CLK_REQ_MASK 0x4
#define SCU_C7_IRQSM_GPS_RF_CLK_REQ(_reg) (((_reg) & 0x4) >> 0x2)
#define SCU_C7_IRQSM_GPS_RF_CLK_REQ_DISABLED \
	(0x0 << SCU_C7_IRQSM_GPS_RF_CLK_REQ_OFFSET)
#define SCU_C7_IRQSM_GPS_RF_CLK_REQ_ENABLED \
	(0x1 << SCU_C7_IRQSM_GPS_RF_CLK_REQ_OFFSET)
#define SCU_C7_IRQSM_GPS_BB_CLK_REQ_OFFSET 0x3
#define SCU_C7_IRQSM_GPS_BB_CLK_REQ_WIDTH 0x1
#define SCU_C7_IRQSM_GPS_BB_CLK_REQ_MASK 0x8
#define SCU_C7_IRQSM_GPS_BB_CLK_REQ(_reg) (((_reg) & 0x8) >> 0x3)
#define SCU_C7_IRQSM_GPS_BB_CLK_REQ_DISABLED \
	(0x0 << SCU_C7_IRQSM_GPS_BB_CLK_REQ_OFFSET)
#define SCU_C7_IRQSM_GPS_BB_CLK_REQ_ENABLED \
	(0x1 << SCU_C7_IRQSM_GPS_BB_CLK_REQ_OFFSET)
#define SCU_C7_IRQSM_GPS_TO_ARM_1_OFFSET 0x4
#define SCU_C7_IRQSM_GPS_TO_ARM_1_WIDTH 0x1
#define SCU_C7_IRQSM_GPS_TO_ARM_1_MASK 0x10
#define SCU_C7_IRQSM_GPS_TO_ARM_1(_reg) (((_reg) & 0x10) >> 0x4)
#define SCU_C7_IRQSM_GPS_TO_ARM_1_DISABLED \
	(0x0 << SCU_C7_IRQSM_GPS_TO_ARM_1_OFFSET)
#define SCU_C7_IRQSM_GPS_TO_ARM_1_ENABLED \
	(0x1 << SCU_C7_IRQSM_GPS_TO_ARM_1_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_0_OFFSET 0x5
#define SCU_C7_IRQSM_GNSS_GPIO_0_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_0_MASK 0x20
#define SCU_C7_IRQSM_GNSS_GPIO_0(_reg) (((_reg) & 0x20) >> 0x5)
#define SCU_C7_IRQSM_GNSS_GPIO_0_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_0_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_0_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_0_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_1_OFFSET 0x6
#define SCU_C7_IRQSM_GNSS_GPIO_1_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_1_MASK 0x40
#define SCU_C7_IRQSM_GNSS_GPIO_1(_reg) (((_reg) & 0x40) >> 0x6)
#define SCU_C7_IRQSM_GNSS_GPIO_1_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_1_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_1_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_1_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_2_OFFSET 0x7
#define SCU_C7_IRQSM_GNSS_GPIO_2_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_2_MASK 0x80
#define SCU_C7_IRQSM_GNSS_GPIO_2(_reg) (((_reg) & 0x80) >> 0x7)
#define SCU_C7_IRQSM_GNSS_GPIO_2_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_2_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_2_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_2_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_3_OFFSET 0x8
#define SCU_C7_IRQSM_GNSS_GPIO_3_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_3_MASK 0x100
#define SCU_C7_IRQSM_GNSS_GPIO_3(_reg) (((_reg) & 0x100) >> 0x8)
#define SCU_C7_IRQSM_GNSS_GPIO_3_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_3_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_3_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_3_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_4_OFFSET 0x9
#define SCU_C7_IRQSM_GNSS_GPIO_4_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_4_MASK 0x200
#define SCU_C7_IRQSM_GNSS_GPIO_4(_reg) (((_reg) & 0x200) >> 0x9)
#define SCU_C7_IRQSM_GNSS_GPIO_4_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_4_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_4_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_4_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_5_OFFSET 0xa
#define SCU_C7_IRQSM_GNSS_GPIO_5_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_5_MASK 0x400
#define SCU_C7_IRQSM_GNSS_GPIO_5(_reg) (((_reg) & 0x400) >> 0xa)
#define SCU_C7_IRQSM_GNSS_GPIO_5_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_5_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_5_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_5_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_6_OFFSET 0xb
#define SCU_C7_IRQSM_GNSS_GPIO_6_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_6_MASK 0x800
#define SCU_C7_IRQSM_GNSS_GPIO_6(_reg) (((_reg) & 0x800) >> 0xb)
#define SCU_C7_IRQSM_GNSS_GPIO_6_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_6_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_6_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_6_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_7_OFFSET 0xc
#define SCU_C7_IRQSM_GNSS_GPIO_7_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_7_MASK 0x1000
#define SCU_C7_IRQSM_GNSS_GPIO_7(_reg) (((_reg) & 0x1000) >> 0xc)
#define SCU_C7_IRQSM_GNSS_GPIO_7_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_7_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_7_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_7_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_8_OFFSET 0xd
#define SCU_C7_IRQSM_GNSS_GPIO_8_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_8_MASK 0x2000
#define SCU_C7_IRQSM_GNSS_GPIO_8(_reg) (((_reg) & 0x2000) >> 0xd)
#define SCU_C7_IRQSM_GNSS_GPIO_8_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_8_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_8_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_8_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_9_OFFSET 0xe
#define SCU_C7_IRQSM_GNSS_GPIO_9_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_9_MASK 0x4000
#define SCU_C7_IRQSM_GNSS_GPIO_9(_reg) (((_reg) & 0x4000) >> 0xe)
#define SCU_C7_IRQSM_GNSS_GPIO_9_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_9_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_9_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_9_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_10_OFFSET 0xf
#define SCU_C7_IRQSM_GNSS_GPIO_10_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_10_MASK 0x8000
#define SCU_C7_IRQSM_GNSS_GPIO_10(_reg) (((_reg) & 0x8000) >> 0xf)
#define SCU_C7_IRQSM_GNSS_GPIO_10_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_10_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_10_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_10_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_11_OFFSET 0x10
#define SCU_C7_IRQSM_GNSS_GPIO_11_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_11_MASK 0x10000
#define SCU_C7_IRQSM_GNSS_GPIO_11(_reg) (((_reg) & 0x10000) >> 0x10)
#define SCU_C7_IRQSM_GNSS_GPIO_11_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_11_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_11_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_11_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_12_OFFSET 0x11
#define SCU_C7_IRQSM_GNSS_GPIO_12_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_12_MASK 0x20000
#define SCU_C7_IRQSM_GNSS_GPIO_12(_reg) (((_reg) & 0x20000) >> 0x11)
#define SCU_C7_IRQSM_GNSS_GPIO_12_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_12_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_12_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_12_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_13_OFFSET 0x12
#define SCU_C7_IRQSM_GNSS_GPIO_13_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_13_MASK 0x40000
#define SCU_C7_IRQSM_GNSS_GPIO_13(_reg) (((_reg) & 0x40000) >> 0x12)
#define SCU_C7_IRQSM_GNSS_GPIO_13_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_13_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_13_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_13_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_14_OFFSET 0x13
#define SCU_C7_IRQSM_GNSS_GPIO_14_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_14_MASK 0x80000
#define SCU_C7_IRQSM_GNSS_GPIO_14(_reg) (((_reg) & 0x80000) >> 0x13)
#define SCU_C7_IRQSM_GNSS_GPIO_14_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_14_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_14_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_14_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_15_OFFSET 0x14
#define SCU_C7_IRQSM_GNSS_GPIO_15_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_15_MASK 0x100000
#define SCU_C7_IRQSM_GNSS_GPIO_15(_reg) (((_reg) & 0x100000) >> 0x14)
#define SCU_C7_IRQSM_GNSS_GPIO_15_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_15_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_15_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_15_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_16_OFFSET 0x15
#define SCU_C7_IRQSM_GNSS_GPIO_16_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_16_MASK 0x200000
#define SCU_C7_IRQSM_GNSS_GPIO_16(_reg) (((_reg) & 0x200000) >> 0x15)
#define SCU_C7_IRQSM_GNSS_GPIO_16_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_16_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_16_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_16_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_17_OFFSET 0x16
#define SCU_C7_IRQSM_GNSS_GPIO_17_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_17_MASK 0x400000
#define SCU_C7_IRQSM_GNSS_GPIO_17(_reg) (((_reg) & 0x400000) >> 0x16)
#define SCU_C7_IRQSM_GNSS_GPIO_17_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_17_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_17_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_17_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_18_OFFSET 0x17
#define SCU_C7_IRQSM_GNSS_GPIO_18_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_18_MASK 0x800000
#define SCU_C7_IRQSM_GNSS_GPIO_18(_reg) (((_reg) & 0x800000) >> 0x17)
#define SCU_C7_IRQSM_GNSS_GPIO_18_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_18_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_18_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_18_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_19_OFFSET 0x18
#define SCU_C7_IRQSM_GNSS_GPIO_19_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_19_MASK 0x1000000
#define SCU_C7_IRQSM_GNSS_GPIO_19(_reg) (((_reg) & 0x1000000) >> 0x18)
#define SCU_C7_IRQSM_GNSS_GPIO_19_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_19_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_19_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_19_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_20_OFFSET 0x19
#define SCU_C7_IRQSM_GNSS_GPIO_20_WIDTH 0x1
#define SCU_C7_IRQSM_GNSS_GPIO_20_MASK 0x2000000
#define SCU_C7_IRQSM_GNSS_GPIO_20(_reg) (((_reg) & 0x2000000) >> 0x19)
#define SCU_C7_IRQSM_GNSS_GPIO_20_DISABLED \
	(0x0 << SCU_C7_IRQSM_GNSS_GPIO_20_OFFSET)
#define SCU_C7_IRQSM_GNSS_GPIO_20_ENABLED \
	(0x1 << SCU_C7_IRQSM_GNSS_GPIO_20_OFFSET)

#define SCU_C7_IRQSS_OFFSET    0x34
#define SCU_C7_IRQSS(_base) ((_base) + 0x34)
#define SCU_C7_IRQSS_GPS_DBG_OFFSET 0x0
#define SCU_C7_IRQSS_GPS_DBG_WIDTH 0x1
#define SCU_C7_IRQSS_GPS_DBG_MASK 0x1
#define SCU_C7_IRQSS_GPS_DBG(_reg) (((_reg) & 0x1) >> 0x0)
#define SCU_C7_IRQSS_GPS_DBG_NO_INTERRUPT (0x0 << SCU_C7_IRQSS_GPS_DBG_OFFSET)
#define SCU_C7_IRQSS_GPS_DBG_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GPS_DBG_OFFSET)
#define SCU_C7_IRQSS_GPS_TCXO_CLK_REQ_OFFSET 0x1
#define SCU_C7_IRQSS_GPS_TCXO_CLK_REQ_WIDTH 0x1
#define SCU_C7_IRQSS_GPS_TCXO_CLK_REQ_MASK 0x2
#define SCU_C7_IRQSS_GPS_TCXO_CLK_REQ(_reg) (((_reg) & 0x2) >> 0x1)
#define SCU_C7_IRQSS_GPS_TCXO_CLK_REQ_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GPS_TCXO_CLK_REQ_OFFSET)
#define SCU_C7_IRQSS_GPS_TCXO_CLK_REQ_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GPS_TCXO_CLK_REQ_OFFSET)
#define SCU_C7_IRQSS_GPS_RF_CLK_REQ_OFFSET 0x2
#define SCU_C7_IRQSS_GPS_RF_CLK_REQ_WIDTH 0x1
#define SCU_C7_IRQSS_GPS_RF_CLK_REQ_MASK 0x4
#define SCU_C7_IRQSS_GPS_RF_CLK_REQ(_reg) (((_reg) & 0x4) >> 0x2)
#define SCU_C7_IRQSS_GPS_RF_CLK_REQ_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GPS_RF_CLK_REQ_OFFSET)
#define SCU_C7_IRQSS_GPS_RF_CLK_REQ_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GPS_RF_CLK_REQ_OFFSET)
#define SCU_C7_IRQSS_GPS_BB_CLK_REQ_OFFSET 0x3
#define SCU_C7_IRQSS_GPS_BB_CLK_REQ_WIDTH 0x1
#define SCU_C7_IRQSS_GPS_BB_CLK_REQ_MASK 0x8
#define SCU_C7_IRQSS_GPS_BB_CLK_REQ(_reg) (((_reg) & 0x8) >> 0x3)
#define SCU_C7_IRQSS_GPS_BB_CLK_REQ_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GPS_BB_CLK_REQ_OFFSET)
#define SCU_C7_IRQSS_GPS_BB_CLK_REQ_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GPS_BB_CLK_REQ_OFFSET)
#define SCU_C7_IRQSS_GPS_TO_ARM_1_OFFSET 0x4
#define SCU_C7_IRQSS_GPS_TO_ARM_1_WIDTH 0x1
#define SCU_C7_IRQSS_GPS_TO_ARM_1_MASK 0x10
#define SCU_C7_IRQSS_GPS_TO_ARM_1(_reg) (((_reg) & 0x10) >> 0x4)
#define SCU_C7_IRQSS_GPS_TO_ARM_1_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GPS_TO_ARM_1_OFFSET)
#define SCU_C7_IRQSS_GPS_TO_ARM_1_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GPS_TO_ARM_1_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_0_OFFSET 0x5
#define SCU_C7_IRQSS_GNSS_GPIO_0_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_0_MASK 0x20
#define SCU_C7_IRQSS_GNSS_GPIO_0(_reg) (((_reg) & 0x20) >> 0x5)
#define SCU_C7_IRQSS_GNSS_GPIO_0_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_0_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_0_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_0_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_1_OFFSET 0x6
#define SCU_C7_IRQSS_GNSS_GPIO_1_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_1_MASK 0x40
#define SCU_C7_IRQSS_GNSS_GPIO_1(_reg) (((_reg) & 0x40) >> 0x6)
#define SCU_C7_IRQSS_GNSS_GPIO_1_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_1_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_1_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_1_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_2_OFFSET 0x7
#define SCU_C7_IRQSS_GNSS_GPIO_2_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_2_MASK 0x80
#define SCU_C7_IRQSS_GNSS_GPIO_2(_reg) (((_reg) & 0x80) >> 0x7)
#define SCU_C7_IRQSS_GNSS_GPIO_2_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_2_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_2_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_2_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_3_OFFSET 0x8
#define SCU_C7_IRQSS_GNSS_GPIO_3_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_3_MASK 0x100
#define SCU_C7_IRQSS_GNSS_GPIO_3(_reg) (((_reg) & 0x100) >> 0x8)
#define SCU_C7_IRQSS_GNSS_GPIO_3_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_3_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_3_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_3_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_4_OFFSET 0x9
#define SCU_C7_IRQSS_GNSS_GPIO_4_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_4_MASK 0x200
#define SCU_C7_IRQSS_GNSS_GPIO_4(_reg) (((_reg) & 0x200) >> 0x9)
#define SCU_C7_IRQSS_GNSS_GPIO_4_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_4_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_4_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_4_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_5_OFFSET 0xa
#define SCU_C7_IRQSS_GNSS_GPIO_5_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_5_MASK 0x400
#define SCU_C7_IRQSS_GNSS_GPIO_5(_reg) (((_reg) & 0x400) >> 0xa)
#define SCU_C7_IRQSS_GNSS_GPIO_5_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_5_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_5_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_5_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_6_OFFSET 0xb
#define SCU_C7_IRQSS_GNSS_GPIO_6_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_6_MASK 0x800
#define SCU_C7_IRQSS_GNSS_GPIO_6(_reg) (((_reg) & 0x800) >> 0xb)
#define SCU_C7_IRQSS_GNSS_GPIO_6_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_6_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_6_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_6_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_7_OFFSET 0xc
#define SCU_C7_IRQSS_GNSS_GPIO_7_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_7_MASK 0x1000
#define SCU_C7_IRQSS_GNSS_GPIO_7(_reg) (((_reg) & 0x1000) >> 0xc)
#define SCU_C7_IRQSS_GNSS_GPIO_7_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_7_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_7_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_7_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_8_OFFSET 0xd
#define SCU_C7_IRQSS_GNSS_GPIO_8_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_8_MASK 0x2000
#define SCU_C7_IRQSS_GNSS_GPIO_8(_reg) (((_reg) & 0x2000) >> 0xd)
#define SCU_C7_IRQSS_GNSS_GPIO_8_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_8_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_8_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_8_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_9_OFFSET 0xe
#define SCU_C7_IRQSS_GNSS_GPIO_9_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_9_MASK 0x4000
#define SCU_C7_IRQSS_GNSS_GPIO_9(_reg) (((_reg) & 0x4000) >> 0xe)
#define SCU_C7_IRQSS_GNSS_GPIO_9_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_9_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_9_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_9_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_10_OFFSET 0xf
#define SCU_C7_IRQSS_GNSS_GPIO_10_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_10_MASK 0x8000
#define SCU_C7_IRQSS_GNSS_GPIO_10(_reg) (((_reg) & 0x8000) >> 0xf)
#define SCU_C7_IRQSS_GNSS_GPIO_10_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_10_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_10_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_10_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_11_OFFSET 0x10
#define SCU_C7_IRQSS_GNSS_GPIO_11_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_11_MASK 0x10000
#define SCU_C7_IRQSS_GNSS_GPIO_11(_reg) (((_reg) & 0x10000) >> 0x10)
#define SCU_C7_IRQSS_GNSS_GPIO_11_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_11_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_11_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_11_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_12_OFFSET 0x11
#define SCU_C7_IRQSS_GNSS_GPIO_12_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_12_MASK 0x20000
#define SCU_C7_IRQSS_GNSS_GPIO_12(_reg) (((_reg) & 0x20000) >> 0x11)
#define SCU_C7_IRQSS_GNSS_GPIO_12_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_12_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_12_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_12_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_13_OFFSET 0x12
#define SCU_C7_IRQSS_GNSS_GPIO_13_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_13_MASK 0x40000
#define SCU_C7_IRQSS_GNSS_GPIO_13(_reg) (((_reg) & 0x40000) >> 0x12)
#define SCU_C7_IRQSS_GNSS_GPIO_13_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_13_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_13_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_13_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_14_OFFSET 0x13
#define SCU_C7_IRQSS_GNSS_GPIO_14_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_14_MASK 0x80000
#define SCU_C7_IRQSS_GNSS_GPIO_14(_reg) (((_reg) & 0x80000) >> 0x13)
#define SCU_C7_IRQSS_GNSS_GPIO_14_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_14_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_14_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_14_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_15_OFFSET 0x14
#define SCU_C7_IRQSS_GNSS_GPIO_15_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_15_MASK 0x100000
#define SCU_C7_IRQSS_GNSS_GPIO_15(_reg) (((_reg) & 0x100000) >> 0x14)
#define SCU_C7_IRQSS_GNSS_GPIO_15_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_15_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_15_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_15_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_16_OFFSET 0x15
#define SCU_C7_IRQSS_GNSS_GPIO_16_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_16_MASK 0x200000
#define SCU_C7_IRQSS_GNSS_GPIO_16(_reg) (((_reg) & 0x200000) >> 0x15)
#define SCU_C7_IRQSS_GNSS_GPIO_16_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_16_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_16_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_16_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_17_OFFSET 0x16
#define SCU_C7_IRQSS_GNSS_GPIO_17_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_17_MASK 0x400000
#define SCU_C7_IRQSS_GNSS_GPIO_17(_reg) (((_reg) & 0x400000) >> 0x16)
#define SCU_C7_IRQSS_GNSS_GPIO_17_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_17_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_17_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_17_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_18_OFFSET 0x17
#define SCU_C7_IRQSS_GNSS_GPIO_18_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_18_MASK 0x800000
#define SCU_C7_IRQSS_GNSS_GPIO_18(_reg) (((_reg) & 0x800000) >> 0x17)
#define SCU_C7_IRQSS_GNSS_GPIO_18_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_18_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_18_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_18_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_19_OFFSET 0x18
#define SCU_C7_IRQSS_GNSS_GPIO_19_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_19_MASK 0x1000000
#define SCU_C7_IRQSS_GNSS_GPIO_19(_reg) (((_reg) & 0x1000000) >> 0x18)
#define SCU_C7_IRQSS_GNSS_GPIO_19_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_19_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_19_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_19_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_20_OFFSET 0x19
#define SCU_C7_IRQSS_GNSS_GPIO_20_WIDTH 0x1
#define SCU_C7_IRQSS_GNSS_GPIO_20_MASK 0x2000000
#define SCU_C7_IRQSS_GNSS_GPIO_20(_reg) (((_reg) & 0x2000000) >> 0x19)
#define SCU_C7_IRQSS_GNSS_GPIO_20_NO_INTERRUPT \
	(0x0 << SCU_C7_IRQSS_GNSS_GPIO_20_OFFSET)
#define SCU_C7_IRQSS_GNSS_GPIO_20_PENDING_INTERRUPT \
	(0x1 << SCU_C7_IRQSS_GNSS_GPIO_20_OFFSET)

#define SCU_C7_IRQSC_OFFSET    0x38
#define SCU_C7_IRQSC(_base) ((_base) + 0x38)
#define SCU_C7_IRQSC_GPS_DBG_OFFSET 0x0
#define SCU_C7_IRQSC_GPS_DBG_WIDTH 0x1
#define SCU_C7_IRQSC_GPS_DBG_MASK 0x1
#define SCU_C7_IRQSC_GPS_DBG(_reg) (((_reg) & 0x1) >> 0x0)
#define SCU_C7_IRQSC_GPS_DBG_NO_CHANGE (0x0 << SCU_C7_IRQSC_GPS_DBG_OFFSET)
#define SCU_C7_IRQSC_GPS_DBG_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GPS_DBG_OFFSET)
#define SCU_C7_IRQSC_GPS_TCXO_CLK_REQ_OFFSET 0x1
#define SCU_C7_IRQSC_GPS_TCXO_CLK_REQ_WIDTH 0x1
#define SCU_C7_IRQSC_GPS_TCXO_CLK_REQ_MASK 0x2
#define SCU_C7_IRQSC_GPS_TCXO_CLK_REQ(_reg) (((_reg) & 0x2) >> 0x1)
#define SCU_C7_IRQSC_GPS_TCXO_CLK_REQ_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GPS_TCXO_CLK_REQ_OFFSET)
#define SCU_C7_IRQSC_GPS_TCXO_CLK_REQ_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GPS_TCXO_CLK_REQ_OFFSET)
#define SCU_C7_IRQSC_GPS_RF_CLK_REQ_OFFSET 0x2
#define SCU_C7_IRQSC_GPS_RF_CLK_REQ_WIDTH 0x1
#define SCU_C7_IRQSC_GPS_RF_CLK_REQ_MASK 0x4
#define SCU_C7_IRQSC_GPS_RF_CLK_REQ(_reg) (((_reg) & 0x4) >> 0x2)
#define SCU_C7_IRQSC_GPS_RF_CLK_REQ_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GPS_RF_CLK_REQ_OFFSET)
#define SCU_C7_IRQSC_GPS_RF_CLK_REQ_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GPS_RF_CLK_REQ_OFFSET)
#define SCU_C7_IRQSC_GPS_BB_CLK_REQ_OFFSET 0x3
#define SCU_C7_IRQSC_GPS_BB_CLK_REQ_WIDTH 0x1
#define SCU_C7_IRQSC_GPS_BB_CLK_REQ_MASK 0x8
#define SCU_C7_IRQSC_GPS_BB_CLK_REQ(_reg) (((_reg) & 0x8) >> 0x3)
#define SCU_C7_IRQSC_GPS_BB_CLK_REQ_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GPS_BB_CLK_REQ_OFFSET)
#define SCU_C7_IRQSC_GPS_BB_CLK_REQ_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GPS_BB_CLK_REQ_OFFSET)
#define SCU_C7_IRQSC_GPS_TO_ARM_1_OFFSET 0x4
#define SCU_C7_IRQSC_GPS_TO_ARM_1_WIDTH 0x1
#define SCU_C7_IRQSC_GPS_TO_ARM_1_MASK 0x10
#define SCU_C7_IRQSC_GPS_TO_ARM_1(_reg) (((_reg) & 0x10) >> 0x4)
#define SCU_C7_IRQSC_GPS_TO_ARM_1_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GPS_TO_ARM_1_OFFSET)
#define SCU_C7_IRQSC_GPS_TO_ARM_1_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GPS_TO_ARM_1_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_0_OFFSET 0x5
#define SCU_C7_IRQSC_GNSS_GPIO_0_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_0_MASK 0x20
#define SCU_C7_IRQSC_GNSS_GPIO_0(_reg) (((_reg) & 0x20) >> 0x5)
#define SCU_C7_IRQSC_GNSS_GPIO_0_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_0_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_0_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_0_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_1_OFFSET 0x6
#define SCU_C7_IRQSC_GNSS_GPIO_1_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_1_MASK 0x40
#define SCU_C7_IRQSC_GNSS_GPIO_1(_reg) (((_reg) & 0x40) >> 0x6)
#define SCU_C7_IRQSC_GNSS_GPIO_1_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_1_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_1_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_1_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_2_OFFSET 0x7
#define SCU_C7_IRQSC_GNSS_GPIO_2_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_2_MASK 0x80
#define SCU_C7_IRQSC_GNSS_GPIO_2(_reg) (((_reg) & 0x80) >> 0x7)
#define SCU_C7_IRQSC_GNSS_GPIO_2_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_2_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_2_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_2_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_3_OFFSET 0x8
#define SCU_C7_IRQSC_GNSS_GPIO_3_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_3_MASK 0x100
#define SCU_C7_IRQSC_GNSS_GPIO_3(_reg) (((_reg) & 0x100) >> 0x8)
#define SCU_C7_IRQSC_GNSS_GPIO_3_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_3_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_3_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_3_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_4_OFFSET 0x9
#define SCU_C7_IRQSC_GNSS_GPIO_4_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_4_MASK 0x200
#define SCU_C7_IRQSC_GNSS_GPIO_4(_reg) (((_reg) & 0x200) >> 0x9)
#define SCU_C7_IRQSC_GNSS_GPIO_4_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_4_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_4_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_4_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_5_OFFSET 0xa
#define SCU_C7_IRQSC_GNSS_GPIO_5_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_5_MASK 0x400
#define SCU_C7_IRQSC_GNSS_GPIO_5(_reg) (((_reg) & 0x400) >> 0xa)
#define SCU_C7_IRQSC_GNSS_GPIO_5_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_5_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_5_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_5_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_6_OFFSET 0xb
#define SCU_C7_IRQSC_GNSS_GPIO_6_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_6_MASK 0x800
#define SCU_C7_IRQSC_GNSS_GPIO_6(_reg) (((_reg) & 0x800) >> 0xb)
#define SCU_C7_IRQSC_GNSS_GPIO_6_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_6_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_6_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_6_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_7_OFFSET 0xc
#define SCU_C7_IRQSC_GNSS_GPIO_7_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_7_MASK 0x1000
#define SCU_C7_IRQSC_GNSS_GPIO_7(_reg) (((_reg) & 0x1000) >> 0xc)
#define SCU_C7_IRQSC_GNSS_GPIO_7_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_7_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_7_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_7_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_8_OFFSET 0xd
#define SCU_C7_IRQSC_GNSS_GPIO_8_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_8_MASK 0x2000
#define SCU_C7_IRQSC_GNSS_GPIO_8(_reg) (((_reg) & 0x2000) >> 0xd)
#define SCU_C7_IRQSC_GNSS_GPIO_8_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_8_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_8_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_8_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_9_OFFSET 0xe
#define SCU_C7_IRQSC_GNSS_GPIO_9_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_9_MASK 0x4000
#define SCU_C7_IRQSC_GNSS_GPIO_9(_reg) (((_reg) & 0x4000) >> 0xe)
#define SCU_C7_IRQSC_GNSS_GPIO_9_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_9_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_9_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_9_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_10_OFFSET 0xf
#define SCU_C7_IRQSC_GNSS_GPIO_10_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_10_MASK 0x8000
#define SCU_C7_IRQSC_GNSS_GPIO_10(_reg) (((_reg) & 0x8000) >> 0xf)
#define SCU_C7_IRQSC_GNSS_GPIO_10_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_10_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_10_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_10_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_11_OFFSET 0x10
#define SCU_C7_IRQSC_GNSS_GPIO_11_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_11_MASK 0x10000
#define SCU_C7_IRQSC_GNSS_GPIO_11(_reg) (((_reg) & 0x10000) >> 0x10)
#define SCU_C7_IRQSC_GNSS_GPIO_11_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_11_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_11_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_11_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_12_OFFSET 0x11
#define SCU_C7_IRQSC_GNSS_GPIO_12_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_12_MASK 0x20000
#define SCU_C7_IRQSC_GNSS_GPIO_12(_reg) (((_reg) & 0x20000) >> 0x11)
#define SCU_C7_IRQSC_GNSS_GPIO_12_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_12_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_12_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_12_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_13_OFFSET 0x12
#define SCU_C7_IRQSC_GNSS_GPIO_13_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_13_MASK 0x40000
#define SCU_C7_IRQSC_GNSS_GPIO_13(_reg) (((_reg) & 0x40000) >> 0x12)
#define SCU_C7_IRQSC_GNSS_GPIO_13_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_13_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_13_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_13_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_14_OFFSET 0x13
#define SCU_C7_IRQSC_GNSS_GPIO_14_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_14_MASK 0x80000
#define SCU_C7_IRQSC_GNSS_GPIO_14(_reg) (((_reg) & 0x80000) >> 0x13)
#define SCU_C7_IRQSC_GNSS_GPIO_14_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_14_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_14_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_14_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_15_OFFSET 0x14
#define SCU_C7_IRQSC_GNSS_GPIO_15_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_15_MASK 0x100000
#define SCU_C7_IRQSC_GNSS_GPIO_15(_reg) (((_reg) & 0x100000) >> 0x14)
#define SCU_C7_IRQSC_GNSS_GPIO_15_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_15_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_15_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_15_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_16_OFFSET 0x15
#define SCU_C7_IRQSC_GNSS_GPIO_16_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_16_MASK 0x200000
#define SCU_C7_IRQSC_GNSS_GPIO_16(_reg) (((_reg) & 0x200000) >> 0x15)
#define SCU_C7_IRQSC_GNSS_GPIO_16_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_16_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_16_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_16_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_17_OFFSET 0x16
#define SCU_C7_IRQSC_GNSS_GPIO_17_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_17_MASK 0x400000
#define SCU_C7_IRQSC_GNSS_GPIO_17(_reg) (((_reg) & 0x400000) >> 0x16)
#define SCU_C7_IRQSC_GNSS_GPIO_17_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_17_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_17_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_17_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_18_OFFSET 0x17
#define SCU_C7_IRQSC_GNSS_GPIO_18_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_18_MASK 0x800000
#define SCU_C7_IRQSC_GNSS_GPIO_18(_reg) (((_reg) & 0x800000) >> 0x17)
#define SCU_C7_IRQSC_GNSS_GPIO_18_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_18_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_18_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_18_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_19_OFFSET 0x18
#define SCU_C7_IRQSC_GNSS_GPIO_19_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_19_MASK 0x1000000
#define SCU_C7_IRQSC_GNSS_GPIO_19(_reg) (((_reg) & 0x1000000) >> 0x18)
#define SCU_C7_IRQSC_GNSS_GPIO_19_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_19_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_19_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_19_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_20_OFFSET 0x19
#define SCU_C7_IRQSC_GNSS_GPIO_20_WIDTH 0x1
#define SCU_C7_IRQSC_GNSS_GPIO_20_MASK 0x2000000
#define SCU_C7_IRQSC_GNSS_GPIO_20(_reg) (((_reg) & 0x2000000) >> 0x19)
#define SCU_C7_IRQSC_GNSS_GPIO_20_NO_CHANGE \
	(0x0 << SCU_C7_IRQSC_GNSS_GPIO_20_OFFSET)
#define SCU_C7_IRQSC_GNSS_GPIO_20_CLEAR_INTERRUPT \
	(0x1 << SCU_C7_IRQSC_GNSS_GPIO_20_OFFSET)

#define SCU_SP_PUR_OFFSET   0x108
#define SCU_SP_PUR(_base) ((_base) + 0x108)
#define SCU_SP_PUR_SP_PUR_OFFSET 0x0
#define SCU_SP_PUR_SP_PUR_WIDTH 0x20
#define SCU_SP_PUR_SP_PUR_MASK 0xffffffff
#define SCU_SP_PUR_SP_PUR(_reg) (((_reg) & 0xffffffff) >> 0x0)

#define SCU_CHIP_ID_OFFSET    0x128
#define SCU_CHIP_ID(_base) ((_base) + 0x128)
#define SCU_CHIP_ID_CHREV_OFFSET 0x0
#define SCU_CHIP_ID_CHREV_WIDTH 0x8
#define SCU_CHIP_ID_CHREV_MASK 0xff
#define SCU_CHIP_ID_CHREV(_reg) (((_reg) & 0xff) >> 0x0)
#define SCU_CHIP_ID_CHID_OFFSET 0x8
#define SCU_CHIP_ID_CHID_WIDTH 0x8
#define SCU_CHIP_ID_CHID_MASK 0xff00
#define SCU_CHIP_ID_CHID(_reg) (((_reg) & 0xff00) >> 0x8)

#define SCU_SP_PUR_OFFSET   0x108
#define SCU_SP_PUR(_base) ((_base) + 0x108)
#define SCU_SP_PUR_SP_PUR(_reg) (((_reg) & 0xffffffff) >> 0x0)
#define SCU_SP_PUR_GNSS_BLANK_OFFSET 0x2
#define SCU_SP_PUR_GNSS_BLANK_RF3G (0x0 << SCU_SP_PUR_GNSS_BLANK_OFFSET)
#define SCU_SP_PUR_GNSS_BLANK_PCL (0x1 << SCU_SP_PUR_GNSS_BLANK_OFFSET)
#define SCU_SP_PUR_EXT_TCXO_OFFSET 0x4
#define SCU_SP_PUR_EXT_TCXO_PAD (0x0 << SCU_SP_PUR_EXT_TCXO_OFFSET)
#define SCU_SP_PUR_EXT_TCXO_LDO (0x1 << SCU_SP_PUR_EXT_TCXO_OFFSET)
#define SCU_SP_PUR_AP_TCXO_REQ_OFFSET 0x5
#define SCU_SP_PUR_AP_TCXO_REQ_NO_REQ (0x0 << SCU_SP_PUR_AP_TCXO_REQ_OFFSET)
#define SCU_SP_PUR_AP_TCXO_REQ_REQ (0x1 << SCU_SP_PUR_AP_TCXO_REQ_OFFSET)

#define SCU_CHIP_ID_OFFSET 0x128
#define SCU_CHIP_ID(_base) ((_base) + 0x128)
#define SCU_CHIP_ID_CHREV_OFFSET 0x0
#define SCU_CHIP_ID_CHREV_WIDTH 0x8
#define SCU_CHIP_ID_CHREV_MASK 0xff
#define SCU_CHIP_ID_CHREV(_reg) (((_reg) & 0xff) >> 0x0)
#define SCU_CHIP_ID_CHID_OFFSET 0x8
#define SCU_CHIP_ID_CHID_WIDTH 0x8
#define SCU_CHIP_ID_CHID_MASK 0xff00
#define SCU_CHIP_ID_CHID(_reg) (((_reg) & 0xff00) >> 0x8)

#endif /* _IMC_IDI_GNSS_REGS_H */

