/*
 * sp0a20 sensor driver
 *
 * Copyright (C) 2012-2014 Intel Mobile Communications GmbH
 *
 * Copyright (C) 2008 Texas Instruments.
 *
 * This file is licensed under the terms of the GNU General Public License
 * version 2. This program is licensed "as is" without any warranty of any
 * kind, whether express or implied.
 *
 * Note:
 *    07/01/2014: new implementation using v4l2-subdev
 *                        instead of v4l2-int-device.
 */

#include <linux/i2c.h>
#include <linux/io.h>
#include <linux/delay.h>
#include <linux/module.h>
#include <media/v4l2-subdev.h>
#include <media/videobuf-core.h>
#include <linux/slab.h>
#include "sp_camera_module.h"
#define SP0A20_DRIVER_NAME "sp0a20"



#define SP0A20_PIDH_ADDR     0x01
#define SP0A20_PIDL_ADDR     0x02


#define SP0A20_HORIZONTAL_START_REG       		0x4a
#define SP0A20_VERTICAL_START_REG           		0x4d



#define SP0A20_HORIZONTAL_OUTPUT_SIZE_HIGH_REG 		0x4e
#define SP0A20_HORIZONTAL_OUTPUT_SIZE_LOW_REG  		0x4f
#define SP0A20_VERTICAL_OUTPUT_SIZE_HIGH_REG   		0x4b
#define SP0A20_VERTICAL_OUTPUT_SIZE_LOW_REG    		0x4c


#define SP0A20_INTEGRATION_TIME_MARGIN 4

#define SP0A20_SW_STREAM				0x92
#define SP0A20_START_STREAMING			0x01
#define SP0A20_STOP_STREAMING			0x00




/* High byte of product ID */
#define SP0A20_PIDH_MAGIC 0x0a
/* Low byte of product ID  */
#define SP0A20_PIDL_MAGIC 0x2b


/* ======================================================================== */
/* Base sensor configs */
/* ======================================================================== */
static const struct sp_camera_module_reg sp0a20_initial_setting[] = {

#if 0
	/*1lanes, 30fps*/
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x36,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x0c,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x92,0x70},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x1b,0x27},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x12,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x13,0x2f},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x6d,0x32},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x6c,0x32},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x6f,0x33},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x6e,0x34},
	  //{SP_CAMERA_MODULE_REG_TYPE_DATA,0x96,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x99,0x04},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x16,0x38},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x17,0x38},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x70,0x3a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x14,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x15,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x71,0x23},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x69,0x25},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x6a,0x1a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x72,0x1c},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x75,0x1e},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x73,0x3c},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x74,0x21},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x79,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x77,0x10},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x1a,0x4d},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x1c,0x07},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x1e,0x15},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x21,0x08},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x22,0x28},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x26,0x66},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x28,0x0b},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x37,0x4a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x01,0x80},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x52,0x10},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x54,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x41,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x42,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x43,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x44,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x03,0x01},//19.2 6-15
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x04,0xc2},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x05,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x06,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x07,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x08,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x09,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x0a,0xb7},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xf0,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xf7,0x4b},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x02,0x10},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x03,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x06,0x4b},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x07,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x08,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x09,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xbe,0xb0},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xbf,0x04},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd0,0xb0},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd1,0x04},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x5a,0x40},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xbc,0x70},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xbd,0x50},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb8,0x68},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb9,0x80},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xba,0x30},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xbb,0x45},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xe0,0x50},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xe1,0x3e},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xe2,0x36},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xe3,0x30},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xe4,0x30},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xe5,0x2e},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xe6,0x2e},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xe7,0x2c},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xe8,0x2c},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xe9,0x2c},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xea,0x2a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xf3,0x2a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xf4,0x2a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x04,0xa0},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x05,0x2a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x0a,0xa0},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x0b,0x2a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xeb,0x7d},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xec,0x7d},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xed,0x05},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xee,0x0a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xf2,0x4d},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x5b,0x05},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x5c,0xa0},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x26,0x80},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x27,0x4f},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x28,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x29,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x2a,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x2b,0x03},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x2c,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x2d,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x30,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x31,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa1,0x15},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa2,0x14},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa3,0x12},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa4,0x12},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa5,0x0d},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa6,0x0c},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa7,0x0a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa8,0x0a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa9,0x0a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xaa,0x0a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xab,0x0a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xac,0x0a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xad,0x04},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xae,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xaf,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb0,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb1,0x04},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb2,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb3,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb4,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb5,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb6,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb7,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb8,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x08,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x09,0x06},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x1d,0x05},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x1f,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x11,0x0a},  
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x32,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x26,0xbf},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x27,0xa2},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xe7,0x03},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xe7,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x1b,0x80},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x1a,0x80},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x18,0x27},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x19,0x26},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x2a,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x2b,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x28,0xf8},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x29,0x08},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x66,0x45},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x67,0x65},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x68,0xdd},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x69,0xfd},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x6a,0xa5},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x7c,0x3c},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x7d,0x5c},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x7e,0xf6},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x7f,0x1b},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x80,0xa6},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x70,0x2b},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x71,0x47},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x72,0x27},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x73,0x47},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x74,0xaa},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x6b,0x0f},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x6c,0x2b},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x6d,0x2b},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x6e,0x4b},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x6f,0xaa},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x61,0xe9},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x62,0x09},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x63,0x50},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x64,0x70},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x65,0x6a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x75,0x80},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x76,0x09},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x77,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x24,0x25},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x0e,0x16},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x3b,0x09},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xde,0x0f},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd7,0x06},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd8,0x06},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd9,0x0a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xda,0x18},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xe8,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xe9,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xea,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xeb,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xec,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xed,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xee,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xef,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd3,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd4,0x28},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd5,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd6,0x08},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd1,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xdc,0x05},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x05,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x81,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfc,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x7d,0x05},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x7e,0x05},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x7f,0x09},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x80,0x08},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xdd,0x0f},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x6d,0x08},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x6e,0x08},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x6f,0x0d},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x70,0x14},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x86,0x18},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x71,0x06},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x72,0x06},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x73,0x0b},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x74,0x14},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x75,0x06},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x76,0x06},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x77,0x0b},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x78,0x14},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x79,0x45},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x7a,0x34},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x7b,0x33},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x7c,0x11},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x81,0x0d},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x82,0x18},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x83,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x84,0x24},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x83,0x12},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x84,0x14},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x86,0x04},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x61,0x60},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x62,0x28},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x8a,0x10},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x8b,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x8c,0x0b},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x8d,0x1a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x8e,0x2c},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x8f,0x39},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x90,0x51},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x91,0x62},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x92,0x71},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x93,0x7a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x94,0x8b},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x95,0x99},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x96,0xa6},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x97,0xb1},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x98,0xbc},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x99,0xc6},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x9a,0xd0},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x9b,0xd9},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x9c,0xe1},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x9d,0xe9},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x9e,0xf1},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x9f,0xf8},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa0,0xff},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x15,0xba},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x16,0xa0},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa0,0x82},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa1,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa2,0xfe},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa3,0xf0},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa4,0x9b},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa5,0xf5},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa6,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa7,0xd4},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa8,0xae},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xa9,0x30},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xaa,0x33},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xab,0x0c},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xac,0x80},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xad,0xe0},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xae,0x1f},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xaf,0xe8},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb0,0x7e},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb1,0x1a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb2,0xf7},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb3,0x9a},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb4,0xef},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb5,0x0c},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb6,0x03},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xb7,0x0f},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd3,0x98},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd4,0x9f},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd5,0x82},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd6,0x68},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd7,0x98},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd8,0x9f},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd9,0x82},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xda,0x68},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xdd,0x30},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xde,0x10},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xdf,0xff},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x00,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xc2,0x88},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xc3,0x66},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xc4,0x44},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xc5,0x22},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xcd,0x10},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xce,0x1f},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xcf,0x30},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd0,0x45},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x30,0x40},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x31,0x60},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x32,0x3f},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x33,0xc0},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x35,0x78},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x36,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x37,0x13},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x0e,0x80},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x0f,0x20},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x10,0x80},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x11,0x80},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x12,0x80},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x13,0x80},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x14,0x8d},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x15,0x8d},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x16,0x86},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x17,0x80},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x31,0x06},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x32,0x15},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x33,0xef},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x34,0x07},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xd2,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfb,0x25},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xf2,0x49},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x35,0x40},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x5d,0x11},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x92,0x00},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
	  {SP_CAMERA_MODULE_REG_TYPE_DATA,0x36,0x00},

#else



	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x36,0x02},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x00},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x0c,0x00},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x92,0x70},// ;before LP11 keep LP00
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x0c,0x00},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x1b,0x27},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x12,0x02},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x13,0x2f},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x6d,0x32},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x6c,0x32},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x6f,0x33},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x6e,0x34},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x99,0x04},//;open driver
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x16,0x38},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x17,0x38},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x70,0x3a},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x14,0x02},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x15,0x20},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x71,0x23},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x69,0x25},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x6a,0x1a},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x72,0x1c},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x75,0x1e},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x73,0x3c},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x74,0x21},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x79,0x00},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x77,0x10},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x1a,0x4d},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x1c,0x07},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x1e,0x15},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x21,0x08},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x22,0x28},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x26,0x66},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x28,0x0b},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x37,0x4a},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x01,0x80},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x50,0xb0},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x51,0x08},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x52,0x03},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x53,0x03},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x54,0x00},
  	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x56,0x03},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//;blacklevel
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x41,0x00},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x42,0x00},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x43,0x00},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x44,0x00},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x00},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x03,0x01},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x04,0xc2},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x05,0x00},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x06,0x00},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x07,0x00},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x08,0x00},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x09,0x01},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x0a,0xb7},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xf0,0x00},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xf7,0x4b},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x02,0x10},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x03,0x01},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x06,0x4b},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x07,0x00},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x08,0x01},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x09,0x00},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xbe,0xb0},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xbf,0x04},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd0,0xb0},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd1,0x04},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x5a,0x40},//;dp rpc   
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},// 
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xbc,0x70},//;rpc_heq_low
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xbd,0x50},//;rpc_heq_dummy
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb8,0x68},//;mean_normal_dummy
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb9,0x80},//;mean_dummy_normal
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xba,0x30},//;mean_dummy_low
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xbb,0x45},//;mean low_dummy
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//;rpc					
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xe0,0x50},//;0x4c;rpc_1base_max
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xe1,0x3e},//;0x3c;rpc_2base_max
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xe2,0x36},//;0x34;rpc_3base_max
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xe3,0x30},//;0x2e;rpc_4base_max
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xe4,0x30},//;0x2e;rpc_5base_max
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xe5,0x2e},//;0x2c;rpc_6base_max
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xe6,0x2e},//;0x2c;rpc_7base_max
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xe7,0x2c},//;0x2a;rpc_8base_max
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xe8,0x2c},//;0x2a;rpc_9base_max
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xe9,0x2c},//;0x2a;rpc_10base_max
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xea,0x2a},//;0x28;rpc_11base_max
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xf3,0x2a},//;0x28;rpc_12base_max
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xf4,0x2a},//;0x28;rpc_13base_max 
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x04,0xa0},//;rpc_max_indr
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x05,0x2a},//;rpc_min_indr 
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x0a,0xa0},//;rpc_max_outdr
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x0b,0x2a},//;rpc_min_outdr
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xeb,0x80},//;target indr
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xec,0x80},//;target outdr
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xed,0x05},//;lock range
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xee,0x0a},//;hold range
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//;??
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xf2,0x4d},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x5b,0x05},//;dp status
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x5c,0xa0},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x26,0x80},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x27,0x4f},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x28,0x00},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x29,0x20},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x2a,0x00},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x2b,0x03},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x2c,0x00},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x2d,0x20},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x30,0x00},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x31,0x00},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//;lsc 1
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa1,0x15},//;12;15;r
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa2,0x14},//;1a;17
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa3,0x12},//;11;11
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa4,0x12},//;0d;10
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa5,0x0d},//;0f;14;g
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa6,0x0c},//;15;14
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa7,0x0a},//;11;11
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa8,0x0a},//;0c;10
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa9,0x0a},//;0e;13;b
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xaa,0x0a},//;14;13
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xab,0x0a},//;0f;0f
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xac,0x0a},//;0c;10
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xad,0x04},//;0c;00;r
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xae,0x02},//;06;06
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xaf,0x02},//;08;06
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb0,0x02},//;06;06
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb1,0x04},//;00;00;g
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb2,0x02},//;00;00;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb3,0x02},//;00;00;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb4,0x02},//;00;00;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb5,0x00},//;00;00;b
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb6,0x00},//;00;00;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb7,0x00},//;00;00;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb8,0x00},//;00;00;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},//;skin detect
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x08,0x00},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x09,0x06},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x1d,0x05},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x1f,0x02},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x11,0x0a},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x32,0x00},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x26,0xbf},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x27,0xa2},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x00},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xe7,0x03},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xe7,0x00},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x1b,0x80},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x1a,0x80},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x18,0x27},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x19,0x26},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x2a,0x00},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x2b,0x00},//;4b
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x28,0xf8},//;6b
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x29,0x08},//;cd
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x66,0x45},//;e7
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x67,0x65},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x68,0xdd},//;47
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x69,0xfd},//;64
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x6a,0xa5},//;f9
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x7c,0x3c},//;12
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x7d,0x5c},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x7e,0xf6},//;2d；32;38
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x7f,0x1b},//;4f;61
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x80,0xa6},//;1d;23
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x70,0x2b},//;37;41
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x71,0x47},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x72,0x27},//;11;10
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x73,0x47},//;2d;38
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x74,0xaa},//;22;2a
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x6b,0x0f},//;43;46
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x6c,0x2b},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x6d,0x2b},//;04;11
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x6e,0x4b},//;20;3a
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x6f,0xaa},//;38;48
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x61,0xe9},//;60;5f
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x62,0x09},//;aa
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x63,0x50},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x64,0x70},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x65,0x6a},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x75,0x80},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x76,0x09},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x77,0x02},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x24,0x25},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x0e,0x16},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x3b,0x09},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x08,0x00},//  
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x09,0x06},// ;sharp_flat_thr 轮廓判断
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xde,0x0f},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd7,0x06},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd8,0x06},// ;sharp_fac_pos 轮廓强度
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd9,0x0a},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xda,0x18},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xe8,0x20},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xe9,0x20},//;18 ;sharp_fac_neg
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xea,0x20},//;18
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xeb,0x20},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xec,0x20},// 
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xed,0x20},//; sharp_ofst_pos
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xee,0x20},//; sharp_ofst_neg
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xef,0x20},//; sharp_ofst_min
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd3,0x20},//; sharp_k_val		  
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd4,0x28},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd5,0x20},//;skin_sharp_delta
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd6,0x08},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//;肤色降锐化 skin_sharp_sel
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd1,0x20},//;排除肤色降`锐化对分辨率卡引起的干扰
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xdc,0x05},//;bpc_ratio_vt
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x05,0x20},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},//;bpc_median_en
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x81,0x00},//;bpc_med_thr
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfc,0x00},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x7d,0x05},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x7e,0x05},// 
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x7f,0x09},//;enable
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x80,0x08},//;沿方向边缘平滑阈值，越小越弱
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},//;dns_flat_dif 强平滑（平坦）区域平滑阈值  0x81↓
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xdd,0x0f},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x6d,0x08},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x6e,0x08},//;dark
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x6f,0x0d},//;dns_edge_dif 弱轮廓（非平坦）区域平滑阈值    0x81↑
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x70,0x14},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x86,0x18},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x71,0x06},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x72,0x06},//;dns_edge_gdif
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x73,0x0b},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x74,0x14},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x75,0x06},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x76,0x06},//;{raw_flat_fac, raw_edge_fac}	
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x77,0x0b},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x78,0x14},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x79,0x45},//;	 
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x7a,0x34},//;2x;dns_flat_thr 根据增益判定区域阈值
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x7b,0x33},//;4x
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x7c,0x11},//;8x
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x81,0x0d},//;16x
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x82,0x18},//;dem  
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x83,0x20},//;{dem_morie_thr, dem_hfmax_thr}
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x84,0x24},//;dem_grad_thr 
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},//;dem_grad_dif
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x83,0x12},//;pf
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x84,0x14},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x86,0x04},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//;	
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x61,0x60},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x62,0x28},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x8a,0x10},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x8b,0x00},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x8c,0x12},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x8d,0x1f},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x8e,0x2e},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x8f,0x40},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x90,0x51},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x91,0x5d},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x92,0x67},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x93,0x73},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x94,0x86},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x95,0x96},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x96,0xa4},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x97,0xb1},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x98,0xbb},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x99,0xc5},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x9a,0xce},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x9b,0xd7},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x9c,0xe1},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x9d,0xe9},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x9e,0xf0},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x9f,0xf8},//;d4;b>th
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa0,0xff},//;a1;r<th  
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},//;a6;(红色接近，肤色不理想)
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x15,0xba},//;f4;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x16,0x96},//;e6;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa0,0x72},//;f4;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa1,0x0c},//;b3;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa2,0x02},//;d9;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa3,0xf7},//;e7;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa4,0xa9},//;cd;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa5,0xe1},//;cc;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa6,0xff},//;3c;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa7,0xe8},//;33;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa8,0x99},//;0f;	  
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa9,0x00},//;99;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xaa,0x33},//;0c;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xab,0x0f},//;db;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xac,0x8c},//;ed;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xad,0xf4},//;b9;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xae,0x00},//;da;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xaf,0xf6},//;d7;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb0,0x99},//;d1;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb1,0xf2},//;d8;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb2,0xfb},//;30;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb3,0xcc},//;33;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb4,0xb9},//;0f;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb5,0x0c},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb6,0x33},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xb7,0x0f},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd3,0x80},//	 
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd4,0x92},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd5,0x70},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd6,0x70},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd7,0x80},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd8,0x92},//;auto_sat
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd9,0x70},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xda,0x70},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//;a0;y_mean_th
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xdd,0x30},//;status
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xde,0x10},//;白色物体表面有彩色噪声降低此值;uv_th
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xdf,0xff},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x00,0x00},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xc2,0x88},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xc3,0x66},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xc4,0x44},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xc5,0x22},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xcd,0x10},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xce,0x1f},//;low_lum_offset
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xcf,0x30},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd0,0x45},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x02},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x30,0x40},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x31,0x60},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x32,0x3f},//;heq						  
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x33,0xc0},//;		
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x35,0x78},//;k_max
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x36,0x20},//;ku_outdoor
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x37,0x13},//;ku_nr
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//;ku_dummy
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x0e,0x80},//;ku_low
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x0f,0x20},//;kl_outdoor 
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x10,0x80},//;kl_nr 	 
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x11,0x80},//;kl_dummy	  
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x12,0x80},//;kl_low		
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x13,0x80},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x14,0x8d},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x15,0x8d},//;auto	 
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x16,0x86},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x17,0x80},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x00},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x31,0x06},//;{contrast sat}
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x32,0x15},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x33,0xef},//;
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x34,0x07},//; 
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xd2,0x01},//;out en
  	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfb,0x25},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xf2,0x49},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x35,0x40},//
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x5d,0x11},//
  	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x00},
  	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x99,0x05},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd,0x01},
  	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x36,0x00},
	#endif 
	};

static const struct sp_camera_module_reg sp0a20_init_tab_VGA_30fps[] = {
	
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd, 0x00},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa2, 0x80},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa3, 0x02},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa4, 0xe0},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xa5, 0x01}, 
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0xfd, 0x01},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x4a, 0x00},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x4b, 0x01},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x4c, 0xe0},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x4d, 0x00},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x4e, 0x02},
	{SP_CAMERA_MODULE_REG_TYPE_DATA,0x4f, 0x80},
	

};



/* ======================================================================== */

static struct sp_camera_module_config sp0a20_configs[] = {
	{
		.name = "0.3MP_15fps",
		.frm_fmt = {
			.width = 640,
			.height = 480,
			.code = V4L2_MBUS_FMT_YUYV8_2X8,
		},
		.frm_intrvl = {
			.interval = {
				.numerator = 1,
				.denominator = 15
			}
		},
		.auto_exp_enabled = false,
		.auto_gain_enabled = false,
		.auto_wb_enabled = false,
		.reg_table = (void *)sp0a20_init_tab_VGA_30fps,
		.reg_table_num_entries =
			sizeof(sp0a20_init_tab_VGA_30fps)
			/
			sizeof(sp0a20_init_tab_VGA_30fps[0])
	},
	
};

/*--------------------------------------------------------------------------*/

static int sp0a20_write_aec(struct sp_camera_module *cam_mod)
{
	int ret = 0;

	sp_camera_module_pr_debug(cam_mod,
			"exp_time = %d, gain = %d, flash_mode = %d\n",
			cam_mod->exp_config.exp_time,
			cam_mod->exp_config.gain,
			cam_mod->exp_config.flash_mode);
	return ret;
} 

/*--------------------------------------------------------------------------*/

static int sp0a20_g_timings(struct sp_camera_module *cam_mod,
	struct sp_camera_module_timings *timings)
{
	int ret 		   = 0;
	u8 reg_val		  = 0;


	if (IS_ERR_OR_NULL(cam_mod->active_config)) {
		goto err;
	}

	
	timings->vt_pix_clk_freq_hz = 26000000;
	timings->line_length_pck = 740;
	timings->frame_length_lines = 640;
	
	timings->coarse_integration_time_min		= 1;
	timings->coarse_integration_time_max_margin = SP0A20_INTEGRATION_TIME_MARGIN;

	/* SP Sensor do not use fine integration time. */
	timings->fine_integration_time_min			= 0;
	timings->fine_integration_time_max_margin	= 0;

	
	timings->binning_factor_x = 1;
	timings->binning_factor_y = 1;


	  sp_camera_module_write_reg(cam_mod, 0xfd, 0x01);

	/* Get the cropping and output resolution to ISP for this mode. */

	sp_camera_module_read_reg(cam_mod, 1, SP0A20_HORIZONTAL_START_REG, &reg_val);
	timings->crop_horizontal_start = reg_val;

	sp_camera_module_read_reg(cam_mod, 1, SP0A20_VERTICAL_START_REG, &reg_val);
	timings->crop_vertical_start = reg_val;

	sp_camera_module_read_reg(cam_mod, 1, SP0A20_HORIZONTAL_OUTPUT_SIZE_HIGH_REG, &reg_val);
	timings->sensor_output_width = reg_val << 8;

	sp_camera_module_read_reg(cam_mod, 1, SP0A20_HORIZONTAL_OUTPUT_SIZE_LOW_REG, &reg_val);
	timings->sensor_output_width |= reg_val;
	timings->sensor_output_width *= 2;

	timings->sensor_output_width = 640;


	sp_camera_module_read_reg(cam_mod, 1, SP0A20_VERTICAL_OUTPUT_SIZE_HIGH_REG, &reg_val);
	timings->sensor_output_height = reg_val << 8;

	sp_camera_module_read_reg(cam_mod, 1, SP0A20_VERTICAL_OUTPUT_SIZE_LOW_REG, &reg_val);
	timings->sensor_output_height |= reg_val;

	timings->sensor_output_height = 480;

	if(timings->binning_factor_x ==1 )
	{
		timings->crop_horizontal_end = timings->sensor_output_width+ timings->crop_horizontal_start-1;
		timings->crop_vertical_end = timings->sensor_output_height + timings->crop_vertical_start-1;
	}
	else if(timings->binning_factor_x ==1 ) //binning
	{
		timings->crop_horizontal_end = timings->sensor_output_width *2+ timings->crop_horizontal_start-1+16;
		timings->crop_vertical_end = timings->sensor_output_height*2 + timings->crop_vertical_start-1+4;

	}


	return ret;

err:
	sp_camera_module_pr_err(cam_mod,
			"failed with error (%d)\n", ret);
	return ret;
}


static int sp0a20_s_wb(struct sp_camera_module *cam_mod)
{
	u32 value = cam_mod->wb_config.preset_id;
	switch (value) {
	case V4L2_WHITE_BALANCE_AUTO:
		sp_camera_module_write_reg(cam_mod, 0xfd, 0x00);
		break;

	case V4L2_WHITE_BALANCE_MANUAL:
	case V4L2_WHITE_BALANCE_INCANDESCENT:
		sp_camera_module_write_reg(cam_mod, 0xfd, 0x00);
		break;
	case V4L2_WHITE_BALANCE_FLUORESCENT:
		/* Home */
		sp_camera_module_write_reg(cam_mod, 0xfd, 0x00);
		break;
	case V4L2_WHITE_BALANCE_FLUORESCENT_H:
	case V4L2_WHITE_BALANCE_HORIZON:
	case V4L2_WHITE_BALANCE_DAYLIGHT:
		/* Office */
		sp_camera_module_write_reg(cam_mod, 0xfd, 0x00);
		break;
	case V4L2_WHITE_BALANCE_FLASH:
	case V4L2_WHITE_BALANCE_CLOUDY:
		/* Cloudy */
		sp_camera_module_write_reg(cam_mod, 0xfd, 0x00);
		break;
	case V4L2_WHITE_BALANCE_SHADE:
	default:
		sp_camera_module_pr_debug(cam_mod,
				"unsupported v4l2 preset wb:%d\n", value);
	break;
	}
	return 0;
}

static int sp0a20_g_exposure(struct sp_camera_module *cam_mod, s32 *value)
{
	u16 shutter;
	u32 expo_pk;

	if (IS_ERR_OR_NULL(cam_mod->active_config))
		return -1;

	sp_camera_module_write_reg(cam_mod, 0xfd, 0x01);

	  
#if 0
	/* read shutter, in number of line period */
	sp_camera_module_read_reg(cam_mod, 1,
			SP0A20_AEC_PK_LONG_EXPO_3RD_REG, &expo_pk);
	shutter = expo_pk & 0xF;

	sp_camera_module_read_reg(cam_mod, 1,
			SP0A20_AEC_PK_LONG_EXPO_2ND_REG, &expo_pk);
	shutter = (shutter << 8) + (expo_pk & 0xFF);

	sp_camera_module_read_reg(cam_mod, 1,
			SP0A20_AEC_PK_LONG_EXPO_1ST_REG, &expo_pk);
	shutter = (shutter << 4) + ((expo_pk >> 4) & 0xF);

	/* T = shutter * 65us */
	*value = shutter * 65 / 1000;
#endif

	*value = 10;

	sp_camera_module_pr_debug(cam_mod,
			"exposure time: %dms shutter: %dus\n", *value, shutter);

	return 0;
}

static int sp0a20_g_iso(struct sp_camera_module *cam_mod, s32 *value)
{
	u32 gain16, reg;

#if 0
	sp_camera_module_read_reg(cam_mod, 1,
			SP0A20_AEC_PK_LONG_GAIN_HIGH_REG, &reg);
	gain16 = reg & 0x07;
	sp_camera_module_read_reg(cam_mod, 1,
			SP0A20_AEC_PK_LONG_GAIN_LOW_REG, &reg);
	gain16 = (gain16 << 8) + (reg & 0xFF);

	*value = gain16 / 16 * 100;
	sp_camera_module_pr_debug(cam_mod, "iso %d\n", *value);
#endif
	*value = 1;
	return 0;
}

static int sp0a20_s_exposure(struct sp_camera_module *cam_mod)
{
	s32 value = cam_mod->exp_config.exp_time;
	switch (value) {
	case -2:
		sp_camera_module_write_reg(cam_mod, 0xfd, 0x00);
		break;
	case -1:
		sp_camera_module_write_reg(cam_mod, 0xfd, 0x00);
		break;
	case 0:
		sp_camera_module_write_reg(cam_mod, 0xfd, 0x00);
		break;
	case 1:
		sp_camera_module_write_reg(cam_mod, 0xfd, 0x00);
		break;

	case 2:
		sp_camera_module_write_reg(cam_mod, 0xfd, 0x00);
		break;
	}
	return 0;
}


/*--------------------------------------------------------------------------*/

static int sp0a20_s_ctrl(struct sp_camera_module *cam_mod, u32 ctrl_id)
{
	int ret = 0;

	sp_camera_module_pr_debug(cam_mod, "\n");

	switch (ctrl_id) {
	case V4L2_CID_GAIN:
		ret = sp0a20_write_aec(cam_mod);
		break;
	case V4L2_CID_EXPOSURE:
		ret = sp0a20_s_exposure(cam_mod);
		break;
	case V4L2_CID_AUTO_N_PRESET_WHITE_BALANCE:
		ret = sp0a20_s_wb(cam_mod);
		break;
	default:
		ret = -EINVAL;
		break;
	}

	if (IS_ERR_VALUE(ret))
		sp_camera_module_pr_debug(cam_mod,
			"failed with error (%d) 0x%x\n", ret, ctrl_id);
	return ret;
}
/*--------------------------------------------------------------------------*/

int sp0a20_g_ctrl(struct v4l2_subdev *sd,
	struct v4l2_control *ctrl)
{
	int ret = 0;
	struct sp_camera_module *cam_mod =
		container_of(sd, struct sp_camera_module, sd);

	sp_camera_module_pr_debug(cam_mod, "\n");

	switch (ctrl->id) {
	case V4L2_CID_GAIN:
	case V4L2_CID_FLASH_LED_MODE:
		/* nothing to be done here */
		break;
	case V4L2_CID_EXPOSURE:
		ret = sp0a20_g_exposure(cam_mod, &ctrl->value);
		break;
	case V4L2_CID_ISO_SENSITIVITY:
		ret = sp0a20_g_iso(cam_mod, &ctrl->value);
		break;
	default:
		break;
	}

	if (IS_ERR_VALUE(ret))
		sp_camera_module_pr_err(cam_mod,
			"failed with error (%d)\n", ret);
	return ret;
}

static int sp0a20_get_ctrl(struct sp_camera_module *cam_mod, u32 ctrl_id)
{
	return 0;
}

/*--------------------------------------------------------------------------*/

static int sp0a20_s_ext_ctrls(struct sp_camera_module *cam_mod,
				 struct sp_camera_module_ext_ctrls *ctrls)
{
	int ret = 0;

	/* Handles only exposure and gain together special case. */
	if (ctrls->count == 1)
		ret = sp0a20_s_ctrl(cam_mod, ctrls->ctrls[0].id);
	else if (ctrls->count == 2 &&
		((ctrls->ctrls[0].id == V4L2_CID_GAIN &&
		ctrls->ctrls[1].id == V4L2_CID_EXPOSURE) ||
		(ctrls->ctrls[1].id == V4L2_CID_GAIN &&
		ctrls->ctrls[0].id == V4L2_CID_EXPOSURE))) {
		ret = sp0a20_write_aec(cam_mod);
		sp0a20_s_exposure(cam_mod);
	} else
		ret = -EINVAL;

	if (IS_ERR_VALUE(ret))
		sp_camera_module_pr_debug(cam_mod,
			"failed with error (%d)\n", ret);

	return ret;
}

/*--------------------------------------------------------------------------*/

static int sp0a20_start_streaming(struct sp_camera_module *cam_mod)
{
	int ret = 0;

	sp_camera_module_pr_debug(cam_mod, "\n");

	
	ret = sp_camera_module_write_reg(cam_mod, 0xfd, 0x00);
	ret = sp_camera_module_write_reg(cam_mod, SP0A20_SW_STREAM, SP0A20_START_STREAMING);
	

	if (IS_ERR_VALUE(ret))
		goto err;

	return 0;
err:
	sp_camera_module_pr_err(cam_mod, "failed with error (%d)\n",
		ret);
	return ret;
}

/*--------------------------------------------------------------------------*/

static int sp0a20_stop_streaming(struct sp_camera_module *cam_mod)
{
	int ret = 0;

	sp_camera_module_pr_debug(cam_mod, "\n");

	
	ret = sp_camera_module_write_reg(cam_mod, 0xfd, 0x00);
	ret = sp_camera_module_write_reg(cam_mod, SP0A20_SW_STREAM, SP0A20_STOP_STREAMING);

	if (IS_ERR_VALUE(ret))
		goto err;

	return 0;
err:
	sp_camera_module_pr_err(cam_mod, "failed with error (%d)\n", ret);
	return ret;
}

/*--------------------------------------------------------------------------*/

static int sp0a20_check_camera_id(struct sp_camera_module *cam_mod)
{
	u8 pidh, pidl;
	int ret = 0;

	sp_camera_module_pr_debug(cam_mod, "\n");

		
	ret = sp_camera_module_write_reg(cam_mod, 0xfd, 0x00);
	ret |= sp_camera_module_read_reg(cam_mod, 1, SP0A20_PIDH_ADDR, &pidh);
	ret |= sp_camera_module_read_reg(cam_mod, 1, SP0A20_PIDL_ADDR, &pidl);

	sp_camera_module_pr_debug(cam_mod,"sp0a20_check_camera_id =  0x0%x%x\n",pidh,pidl);

	if (IS_ERR_VALUE(ret)) {
		sp_camera_module_pr_err(cam_mod,
			"register read failed, camera module powered off?\n");
		goto err;
	}

	if ((pidh == SP0A20_PIDH_MAGIC) && (pidl == SP0A20_PIDL_MAGIC))
		sp_camera_module_pr_debug(cam_mod,
			"successfully detected camera ID 0x%02x%02x\n",
			pidh, pidl);
	else {
		sp_camera_module_pr_err(cam_mod,
			"wrong camera ID, expected 0x%02x%02x, detected 0x%02x%02x\n",
			SP0A20_PIDH_MAGIC, SP0A20_PIDL_MAGIC, pidh, pidl);
		ret = -EINVAL;
		goto err;
	}

	/* writing initialize registers */
	ret = sp_camera_module_write_reglist(cam_mod, sp0a20_initial_setting,
			sizeof(sp0a20_initial_setting)
			/ sizeof(sp0a20_initial_setting[0]));

	
	if (IS_ERR_VALUE(ret)) {
		sp_camera_module_pr_err(cam_mod,
			"write initial setting error\n");
		goto err;
	}

	return 0;
err:
	sp_camera_module_pr_err(cam_mod, "failed with error (%d)\n", ret);
	return ret;
}

/* ======================================================================== */
/* This part is platform dependent */
/* ======================================================================== */

static struct v4l2_subdev_core_ops sp0a20_camera_module_core_ops = {
	.g_ctrl = sp0a20_g_ctrl,
	.s_ctrl = sp_camera_module_s_ctrl,
	.s_ext_ctrls = sp_camera_module_s_ext_ctrls,
	.s_power = sp_camera_module_s_power,
	.ioctl = sp_camera_module_ioctl
};

static struct v4l2_subdev_video_ops sp0a20_camera_module_video_ops = {
	.enum_frameintervals = sp_camera_module_enum_frameintervals,
	.s_mbus_fmt = sp_camera_module_s_fmt,
	.g_mbus_fmt = sp_camera_module_g_fmt,
	.try_mbus_fmt = sp_camera_module_try_fmt,
	.s_frame_interval = sp_camera_module_s_frame_interval,
	.s_stream = sp_camera_module_s_stream
};

static struct v4l2_subdev_ops sp0a20_camera_module_ops = {
	.core = &sp0a20_camera_module_core_ops,
	.video = &sp0a20_camera_module_video_ops
};

static struct sp_camera_module sp0a20;

static struct sp_camera_module_custom_config sp0a20_custom_config = {/*{{{*/
	.start_streaming = sp0a20_start_streaming,
	.stop_streaming = sp0a20_stop_streaming,
	.s_ctrl = sp0a20_s_ctrl,
	.s_ext_ctrls = sp0a20_s_ext_ctrls,
	.g_ctrl = sp0a20_get_ctrl,
	.g_timings = sp0a20_g_timings,
	.check_camera_id = sp0a20_check_camera_id,
	.configs = sp0a20_configs,
	.num_configs = sizeof(sp0a20_configs) / sizeof(sp0a20_configs[0]),
	.power_up_delays_ms = {5, 20, 0}
};

static int __init sp0a20_probe(
	struct i2c_client *client,
	const struct i2c_device_id *id)
{
	int ret = 0;

	dev_info(&client->dev, "probing...\n");

	v4l2_i2c_subdev_init(&sp0a20.sd, client, &sp0a20_camera_module_ops);
	ret = sp_camera_module_init(&sp0a20,
			&sp0a20_custom_config);
	if (IS_ERR_VALUE(ret))
		goto err;

	sp_camera_module_s_power(&sp0a20.sd, 1);


	sp_camera_module_s_power(&sp0a20.sd, 0);

	dev_info(&client->dev, "probing successful\n");
	return 0;
err:
	dev_err(&client->dev, "probing failed with error (%d)\n", ret);
	return ret;
} /*}}}*/

/* ======================================================================== */

static int __exit sp0a20_remove(
	struct i2c_client *client)
{
	struct sp_camera_module *cam_mod = i2c_get_clientdata(client);

	dev_info(&client->dev, "remsping device...\n");

	if (!client->adapter)
		return -ENODEV;	/* our client isn't attached */

	sp_camera_module_release(cam_mod);

	dev_info(&client->dev, "removed\n");
	return 0;
} 

static const struct i2c_device_id sp0a20_id[] = {
	{ SP0A20_DRIVER_NAME, 0 },
	{ }
};

static struct of_device_id sp0a20_of_match[] = {
	{.compatible = "superpix," SP0A20_DRIVER_NAME "-v4l2-i2c-subdev",},
	{},
};

MODULE_DEVICE_TABLE(i2c, sp0a20_id);

static struct i2c_driver sp0a20_i2c_driver = {
	.driver = {
		.name = SP0A20_DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table = sp0a20_of_match
	},
	.probe = sp0a20_probe,
	.remove = __exit_p(sp0a20_remove),
	.id_table = sp0a20_id,
};

module_i2c_driver(sp0a20_i2c_driver);

MODULE_DESCRIPTION("SoC Camera driver for sp0a20");
MODULE_AUTHOR("Eike Grimpe");
MODULE_LICENSE("GPL");
/*}}}*/
