obj-$(CONFIG_FB_ROCKCHIP) += rockchip_disp_drv.o rockchip_fb.o rockchip_fb_sysfs.o rockchip_screen.o
obj-$(CONFIG_FB_ROCKCHIP) += vop/
obj-$(CONFIG_RGA_ROCKCHIP) += rga/
obj-$(CONFIG_RK_HDMI) += display-sys.o hdmi/
obj-$(CONFIG_LVDS_RK61X) += rk61x_lvds.o
