# gsensor drivers

obj-$(CONFIG_PS_AL3006) 		+= ps_al3006.o
obj-$(CONFIG_PS_STK3171) 		+= ps_stk3171.o
obj-$(CONFIG_PS_AP321XX) 		+= ps_ap321xx.o
obj-$(CONFIG_PS_TMD2772)  		+= ps_tmd2772.o
obj-$(CONFIG_PS_CM36682)  		+= ps_cm36682.o
obj-$(CONFIG_PS_RPR0521)  		+= ps_rpr0521.o
