#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_WIRELESS 1
#define CPTCFG_NET_CORE 1
#define CPTCFG_EXPERT 1
#define CPTCFG_BACKPORT_FW_LOADER 1
#define CPTCFG_BACKPORT_BUILD_GENERIC_ATOMIC64 1
#define CPTCFG_BACKPORT_OPTION_BT_SOCK_CREATE_NEEDS_KERN 1
#define CPTCFG_BACKPORT_AVERAGE 1
//#define CPTCFG_BACKPORT_BUILD_LEDS 1
//#define CPTCFG_BACKPORT_LEDS_TRIGGERS 1
//#define CPTCFG_MAC80211_LEDS 1
//#define CPTCFG_IWLWIFI_LEDS 1
#define CPTCFG_CFG80211_MODULE 1
#define CPTCFG_NL80211_TESTMODE 1
#define CPTCFG_CFG80211_CERTIFICATION_ONUS 1
#define CPTCFG_CFG80211_REG_CELLULAR_HINTS 1
#define CPTCFG_CFG80211_REG_RELAX_NO_IR 1
#define CPTCFG_CFG80211_DEFAULT_PS 1
#define CPTCFG_CFG80211_DEBUGFS 1
#define CPTCFG_CFG80211_ANDROID_P2P_HACK 1
#define CPTCFG_MAC80211_MODULE 1
#define CPTCFG_MAC80211_HAS_RC 1
#define CPTCFG_MAC80211_RC_MINSTREL 1
#define CPTCFG_MAC80211_RC_MINSTREL_HT 1
#define CPTCFG_MAC80211_RC_DEFAULT_MINSTREL 1
#define CPTCFG_MAC80211_RC_DEFAULT "minstrel_ht"
#define CPTCFG_MAC80211_DEBUGFS 1
#define CPTCFG_MAC80211_MESSAGE_TRACING 1
#define CPTCFG_WLAN 1
#define CPTCFG_IWLWIFI_MODULE 1
#define CPTCFG_IWLMVM_MODULE 1
#define CPTCFG_IWLWIFI_OPMODE_MODULAR 1
#define CPTCFG_IWLWIFI_SDIO 1
#define CPTCFG_IWLWIFI_BCAST_FILTERING 1
#define CPTCFG_IWLWIFI_DEBUG 1
#define CPTCFG_IWLWIFI_DEBUGFS 1
#define CPTCFG_IWLWIFI_DEVICE_TRACING 1
#define CPTCFG_IWLXVT_MODULE 1
#define CPTCFG_IWLWIFI_IDI 1
#define CPTCFG_IWLWIFI_NUM_CHANNELS 1
#define CPTCFG_IWLMVM_POWER_SCHEME 2
#define CPTCFG_IWLWIFI_DEVICE_TESTMODE 1
#define CPTCFG_IWLWIFI_FRQ_MGR 1
#define CPTCFG_IWLWIFI_SUPPORT_DEBUG_OVERRIDES 1
#define CPTCFG_IWLWIFI_MINI_PM_RUNTIME 1
#define CPTCFG_IWLMVM_P2P_OPPPS_TEST_WA 1
#define CPTCFG_IWLMVM_TCM 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
